import 'subject.dart';
import 'exercise_type.dart';
import 'unit.dart';
import 'skill.dart';
import 'item.dart';

// ─── Units ───────────────────────────────────────────────────────────────────

final List<Unit> englishCambridgeUnits = [
  Unit(id: 'ENG-E1', subject: Subject.ENGLISH, code: 'ENG-E1', title: 'Alphabet & Phonics Basics (LKG)', skillIds: ['es10', 'es11', 'es12', 'es13']),
  Unit(id: 'ENG-E2', subject: Subject.ENGLISH, code: 'ENG-E2', title: 'Short Vowels & CVC Words', skillIds: ['es14', 'es15', 'es16', 'es17', 'es18']),
  Unit(id: 'ENG-E3', subject: Subject.ENGLISH, code: 'ENG-E3', title: 'Long Vowels & CVCe Words', skillIds: ['es19', 'es20', 'es21', 'es22']),
  Unit(id: 'ENG-E4', subject: Subject.ENGLISH, code: 'ENG-E4', title: 'Blends & Digraphs', skillIds: ['es23', 'es24', 'es25', 'es26']),
  Unit(id: 'ENG-E5', subject: Subject.ENGLISH, code: 'ENG-E5', title: 'Sight Words', skillIds: ['es27', 'es28', 'es29']),
  Unit(id: 'ENG-E6', subject: Subject.ENGLISH, code: 'ENG-E6', title: 'Spelling & Word Building', skillIds: ['es30', 'es31', 'es32']),
  Unit(id: 'ENG-E7', subject: Subject.ENGLISH, code: 'ENG-E7', title: 'Sentences & Grammar', skillIds: ['es33', 'es34', 'es35', 'es36']),
  Unit(id: 'ENG-E8', subject: Subject.ENGLISH, code: 'ENG-E8', title: 'Reading & Comprehension', skillIds: ['es37', 'es38']),
  Unit(id: 'ENG-E9', subject: Subject.ENGLISH, code: 'ENG-E9', title: 'Vocabulary & Spelling', skillIds: ['es39', 'es40', 'es41']),
  Unit(id: 'ENG-E10', subject: Subject.ENGLISH, code: 'ENG-E10', title: 'Singular, Plural & Matching', skillIds: ['es42', 'es43', 'es44', 'es45']),
  Unit(id: 'ENG-E11', subject: Subject.ENGLISH, code: 'ENG-E11', title: 'Sentence Building & More', skillIds: ['es46', 'es47', 'es48', 'es49']),
];

// ─── Skills ──────────────────────────────────────────────────────────────────

final List<Skill> englishCambridgeSkills = [
  // Unit E1
  Skill(id: 'es10', subject: Subject.ENGLISH, unitCode: 'ENG-E1', title: 'Uppercase Letters', icon: '🔤', prerequisites: [], itemIds: ['ei100','ei101','ei102','ei103','ei104','ei105','ei106','ei107']),
  Skill(id: 'es11', subject: Subject.ENGLISH, unitCode: 'ENG-E1', title: 'Lowercase Letters', icon: '🔡', prerequisites: ['es10'], itemIds: ['ei108','ei109','ei110','ei111','ei112','ei113','ei114','ei115']),
  Skill(id: 'es12', subject: Subject.ENGLISH, unitCode: 'ENG-E1', title: 'Letter Sounds (a-m)', icon: '🔊', prerequisites: ['es10'], itemIds: ['ei116','ei117','ei118','ei119','ei120','ei121','ei122','ei123']),
  Skill(id: 'es13', subject: Subject.ENGLISH, unitCode: 'ENG-E1', title: 'Letter Sounds (n-z)', icon: '🔊', prerequisites: ['es12'], itemIds: ['ei124','ei125','ei126','ei127','ei128','ei129','ei130','ei131']),
  // Unit E2
  Skill(id: 'es14', subject: Subject.ENGLISH, unitCode: 'ENG-E2', title: 'Short a Words', icon: '🐱', prerequisites: ['es13'], itemIds: ['ei132','ei133','ei134','ei135','ei136','ei137','ei138','ei139','ei140','ei141']),
  Skill(id: 'es15', subject: Subject.ENGLISH, unitCode: 'ENG-E2', title: 'Short e Words', icon: '🐔', prerequisites: ['es13'], itemIds: ['ei142','ei143','ei144','ei145','ei146','ei147','ei148','ei149','ei150','ei151']),
  Skill(id: 'es16', subject: Subject.ENGLISH, unitCode: 'ENG-E2', title: 'Short i Words', icon: '🐷', prerequisites: ['es13'], itemIds: ['ei152','ei153','ei154','ei155','ei156','ei157','ei158','ei159','ei160','ei161']),
  Skill(id: 'es17', subject: Subject.ENGLISH, unitCode: 'ENG-E2', title: 'Short o Words', icon: '🐶', prerequisites: ['es13'], itemIds: ['ei162','ei163','ei164','ei165','ei166','ei167','ei168','ei169','ei170','ei171']),
  Skill(id: 'es18', subject: Subject.ENGLISH, unitCode: 'ENG-E2', title: 'Short u Words', icon: '🐛', prerequisites: ['es13'], itemIds: ['ei172','ei173','ei174','ei175','ei176','ei177','ei178','ei179','ei180','ei181']),
  // Unit E3
  Skill(id: 'es19', subject: Subject.ENGLISH, unitCode: 'ENG-E3', title: 'Magic e - Long a', icon: '🎂', prerequisites: ['es14'], itemIds: ['ei182','ei183','ei184','ei185','ei186','ei187','ei188','ei189']),
  Skill(id: 'es20', subject: Subject.ENGLISH, unitCode: 'ENG-E3', title: 'Magic e - Long i', icon: '🚲', prerequisites: ['es16'], itemIds: ['ei190','ei191','ei192','ei193','ei194','ei195','ei196','ei197']),
  Skill(id: 'es21', subject: Subject.ENGLISH, unitCode: 'ENG-E3', title: 'Magic e - Long o', icon: '🏠', prerequisites: ['es17'], itemIds: ['ei198','ei199','ei200','ei201','ei202','ei203','ei204','ei205']),
  Skill(id: 'es22', subject: Subject.ENGLISH, unitCode: 'ENG-E3', title: 'Magic e - Long u', icon: '🎵', prerequisites: ['es18'], itemIds: ['ei206','ei207','ei208','ei209','ei210','ei211','ei212','ei213']),
  // Unit E4
  Skill(id: 'es23', subject: Subject.ENGLISH, unitCode: 'ENG-E4', title: 'L-Blends (bl, cl, fl, gl)', icon: '🌿', prerequisites: ['es14'], itemIds: ['ei214','ei215','ei216','ei217','ei218','ei219','ei220','ei221']),
  Skill(id: 'es24', subject: Subject.ENGLISH, unitCode: 'ENG-E4', title: 'R-Blends (br, cr, dr, fr, gr)', icon: '🌲', prerequisites: ['es15'], itemIds: ['ei222','ei223','ei224','ei225','ei226','ei227','ei228','ei229']),
  Skill(id: 'es25', subject: Subject.ENGLISH, unitCode: 'ENG-E4', title: 'S-Blends (sk, sl, sm, sn, sp, st)', icon: '🐍', prerequisites: ['es16'], itemIds: ['ei230','ei231','ei232','ei233','ei234','ei235','ei236','ei237']),
  Skill(id: 'es26', subject: Subject.ENGLISH, unitCode: 'ENG-E4', title: 'Digraphs (sh, ch, th, wh)', icon: '🤫', prerequisites: ['es23'], itemIds: ['ei238','ei239','ei240','ei241','ei242','ei243','ei244','ei245','ei246','ei247','ei248','ei249']),
  // Unit E5
  Skill(id: 'es27', subject: Subject.ENGLISH, unitCode: 'ENG-E5', title: 'Dolch Pre-Primer', icon: '📖', prerequisites: ['es12'], itemIds: ['ei250','ei251','ei252','ei253','ei254','ei255','ei256','ei257','ei258','ei259']),
  Skill(id: 'es28', subject: Subject.ENGLISH, unitCode: 'ENG-E5', title: 'Dolch Primer', icon: '📖', prerequisites: ['es27'], itemIds: ['ei260','ei261','ei262','ei263','ei264','ei265','ei266','ei267','ei268','ei269']),
  Skill(id: 'es29', subject: Subject.ENGLISH, unitCode: 'ENG-E5', title: 'Common Words', icon: '📖', prerequisites: ['es28'], itemIds: ['ei270','ei271','ei272','ei273','ei274','ei275','ei276','ei277','ei278','ei279']),
  // Unit E6
  Skill(id: 'es30', subject: Subject.ENGLISH, unitCode: 'ENG-E6', title: 'Fill in the Blanks', icon: '✏️', prerequisites: ['es14'], itemIds: ['ei280','ei281','ei282','ei283','ei284','ei285','ei286','ei287','ei288','ei289']),
  Skill(id: 'es31', subject: Subject.ENGLISH, unitCode: 'ENG-E6', title: 'Spelling from Picture', icon: '🖼️', prerequisites: ['es14'], itemIds: ['ei290','ei291','ei292','ei293','ei294','ei295','ei296','ei297']),
  Skill(id: 'es32', subject: Subject.ENGLISH, unitCode: 'ENG-E6', title: 'Rhyming Words', icon: '🎵', prerequisites: ['es14'], itemIds: ['ei298','ei299','ei300','ei301','ei302','ei303','ei304','ei305']),
  // Unit E7
  Skill(id: 'es33', subject: Subject.ENGLISH, unitCode: 'ENG-E7', title: 'Articles (a, an, the)', icon: '📝', prerequisites: ['es27'], itemIds: ['ei306','ei307','ei308','ei309','ei310','ei311','ei312','ei313']),
  Skill(id: 'es34', subject: Subject.ENGLISH, unitCode: 'ENG-E7', title: 'Plurals', icon: '📝', prerequisites: ['es27'], itemIds: ['ei314','ei315','ei316','ei317','ei318','ei319','ei320','ei321']),
  Skill(id: 'es35', subject: Subject.ENGLISH, unitCode: 'ENG-E7', title: 'Build a Sentence', icon: '✏️', prerequisites: ['es29'], itemIds: ['ei322','ei323','ei324','ei325','ei326','ei327']),
  Skill(id: 'es36', subject: Subject.ENGLISH, unitCode: 'ENG-E7', title: 'Opposites', icon: '↕️', prerequisites: ['es27'], itemIds: ['ei328','ei329','ei330','ei331','ei332','ei333','ei334','ei335']),
  // Unit E8
  Skill(id: 'es37', subject: Subject.ENGLISH, unitCode: 'ENG-E8', title: 'Short Stories', icon: '📚', prerequisites: ['es35'], itemIds: ['ei336','ei337','ei338','ei339','ei340','ei341']),
  Skill(id: 'es38', subject: Subject.ENGLISH, unitCode: 'ENG-E8', title: 'Sequencing', icon: '🔢', prerequisites: ['es35'], itemIds: ['ei342','ei343','ei344','ei345','ei346','ei347']),
  // Unit E9 - Vocabulary & Spelling
  Skill(id: 'es39', subject: Subject.ENGLISH, unitCode: 'ENG-E9', title: 'Missing Letters', icon: '✏️', prerequisites: ['es14'], itemIds: ['ei348','ei349','ei350','ei351','ei352','ei353','ei354','ei355','ei356','ei357','ei358','ei359']),
  Skill(id: 'es40', subject: Subject.ENGLISH, unitCode: 'ENG-E9', title: 'Spelling Challenge', icon: '🏆', prerequisites: ['es30'], itemIds: ['ei360','ei361','ei362','ei363','ei364','ei365','ei366','ei367','ei368','ei369','ei370','ei371']),
  Skill(id: 'es41', subject: Subject.ENGLISH, unitCode: 'ENG-E9', title: 'Vocabulary Builder', icon: '📚', prerequisites: ['es29'], itemIds: ['ei372','ei373','ei374','ei375','ei376','ei377','ei378','ei379','ei380','ei381']),
  // Unit E10 - Singular, Plural & Matching
  Skill(id: 'es42', subject: Subject.ENGLISH, unitCode: 'ENG-E10', title: 'Regular Plurals', icon: '👯', prerequisites: ['es27'], itemIds: ['ei382','ei383','ei384','ei385','ei386','ei387','ei388','ei389','ei390','ei391','ei392','ei393']),
  Skill(id: 'es43', subject: Subject.ENGLISH, unitCode: 'ENG-E10', title: 'Irregular Plurals', icon: '🔄', prerequisites: ['es42'], itemIds: ['ei394','ei395','ei396','ei397','ei398','ei399','ei400','ei401','ei402','ei403']),
  Skill(id: 'es44', subject: Subject.ENGLISH, unitCode: 'ENG-E10', title: 'Word Matching', icon: '🔗', prerequisites: ['es27'], itemIds: ['ei404','ei405','ei406','ei407','ei408','ei409','ei410','ei411','ei412','ei413']),
  Skill(id: 'es45', subject: Subject.ENGLISH, unitCode: 'ENG-E10', title: 'Category Matching', icon: '🏷️', prerequisites: ['es29'], itemIds: ['ei414','ei415','ei416','ei417','ei418','ei419','ei420','ei421','ei422','ei423']),
  // Unit E11 - Sentence Building & More
  Skill(id: 'es46', subject: Subject.ENGLISH, unitCode: 'ENG-E11', title: 'Build More Sentences', icon: '✏️', prerequisites: ['es35'], itemIds: ['ei424','ei425','ei426','ei427','ei428','ei429','ei430','ei431','ei432','ei433']),
  Skill(id: 'es47', subject: Subject.ENGLISH, unitCode: 'ENG-E11', title: 'Word Order', icon: '📝', prerequisites: ['es35'], itemIds: ['ei434','ei435','ei436','ei437','ei438','ei439','ei440','ei441']),
  Skill(id: 'es48', subject: Subject.ENGLISH, unitCode: 'ENG-E11', title: 'Vocabulary in Context', icon: '🧠', prerequisites: ['es41'], itemIds: ['ei442','ei443','ei444','ei445','ei446','ei447','ei448','ei449','ei450','ei451']),
  Skill(id: 'es49', subject: Subject.ENGLISH, unitCode: 'ENG-E11', title: 'Picture-Word Matching', icon: '🖼️', prerequisites: ['es29'], itemIds: ['ei452','ei453','ei454','ei455','ei456','ei457','ei458','ei459','ei460','ei461']),
];

// ─── Items ───────────────────────────────────────────────────────────────────

final List<Item> englishCambridgeItems = [
  // ═══════════════════════════════════════════════════════════════════════════
  // es10 – Uppercase Letters (8 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei100', skillId: 'es10', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which letter is A?'),
      answer: ['A'], distractors: ['O', 'Q', 'U']),
  Item(id: 'ei101', skillId: 'es10', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which letter is B?'),
      answer: ['B'], distractors: ['D', 'P', 'R']),
  Item(id: 'ei102', skillId: 'es10', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which letter is E?'),
      answer: ['E'], distractors: ['F', 'C', 'H']),
  Item(id: 'ei103', skillId: 'es10', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which letter is M?'),
      answer: ['M'], distractors: ['N', 'W', 'H']),
  Item(id: 'ei104', skillId: 'es10', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which letter is S?'),
      answer: ['S'], distractors: ['Z', 'C', 'X']),
  Item(id: 'ei105', skillId: 'es10', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which letter is T?'),
      answer: ['T'], distractors: ['L', 'I', 'J']),
  Item(id: 'ei106', skillId: 'es10', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which letter is G?'),
      answer: ['G'], distractors: ['C', 'O', 'Q']),
  Item(id: 'ei107', skillId: 'es10', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which letter is K?'),
      answer: ['K'], distractors: ['X', 'H', 'R']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es11 – Lowercase Letters (8 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei108', skillId: 'es11', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which letter is a?'),
      answer: ['a'], distractors: ['o', 'e', 'u']),
  Item(id: 'ei109', skillId: 'es11', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which letter is b?'),
      answer: ['b'], distractors: ['d', 'p', 'h']),
  Item(id: 'ei110', skillId: 'es11', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which letter is p?'),
      answer: ['p'], distractors: ['q', 'b', 'd']),
  Item(id: 'ei111', skillId: 'es11', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which letter is m?'),
      answer: ['m'], distractors: ['n', 'w', 'r']),
  Item(id: 'ei112', skillId: 'es11', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which letter is f?'),
      answer: ['f'], distractors: ['t', 'l', 'j']),
  Item(id: 'ei113', skillId: 'es11', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which letter is s?'),
      answer: ['s'], distractors: ['z', 'c', 'x']),
  Item(id: 'ei114', skillId: 'es11', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which letter is g?'),
      answer: ['g'], distractors: ['q', 'y', 'j']),
  Item(id: 'ei115', skillId: 'es11', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which letter is u?'),
      answer: ['u'], distractors: ['v', 'n', 'w']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es12 – Letter Sounds (a-m) (8 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei116', skillId: 'es12', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What sound does A make?'),
      answer: ['ah'], distractors: ['oh', 'eh', 'oo']),
  Item(id: 'ei117', skillId: 'es12', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What sound does B make?'),
      answer: ['buh'], distractors: ['duh', 'puh', 'guh']),
  Item(id: 'ei118', skillId: 'es12', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What sound does C make?'),
      answer: ['kuh'], distractors: ['suh', 'chuh', 'buh']),
  Item(id: 'ei119', skillId: 'es12', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What sound does D make?'),
      answer: ['duh'], distractors: ['buh', 'tuh', 'puh']),
  Item(id: 'ei120', skillId: 'es12', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What sound does F make?'),
      answer: ['fuh'], distractors: ['vuh', 'puh', 'suh']),
  Item(id: 'ei121', skillId: 'es12', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What sound does H make?'),
      answer: ['huh'], distractors: ['wuh', 'yuh', 'fuh']),
  Item(id: 'ei122', skillId: 'es12', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What sound does L make?'),
      answer: ['luh'], distractors: ['ruh', 'muh', 'nuh']),
  Item(id: 'ei123', skillId: 'es12', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What sound does M make?'),
      answer: ['muh'], distractors: ['nuh', 'luh', 'buh']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es13 – Letter Sounds (n-z) (8 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei124', skillId: 'es13', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What sound does N make?'),
      answer: ['nuh'], distractors: ['muh', 'luh', 'nguh']),
  Item(id: 'ei125', skillId: 'es13', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What sound does P make?'),
      answer: ['puh'], distractors: ['buh', 'duh', 'tuh']),
  Item(id: 'ei126', skillId: 'es13', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What sound does R make?'),
      answer: ['ruh'], distractors: ['luh', 'wuh', 'nuh']),
  Item(id: 'ei127', skillId: 'es13', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What sound does S make?'),
      answer: ['sss'], distractors: ['zzz', 'shh', 'fuh']),
  Item(id: 'ei128', skillId: 'es13', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What sound does T make?'),
      answer: ['tuh'], distractors: ['duh', 'puh', 'buh']),
  Item(id: 'ei129', skillId: 'es13', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What sound does W make?'),
      answer: ['wuh'], distractors: ['vuh', 'yuh', 'huh']),
  Item(id: 'ei130', skillId: 'es13', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What sound does Y make?'),
      answer: ['yuh'], distractors: ['wuh', 'jeh', 'huh']),
  Item(id: 'ei131', skillId: 'es13', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What sound does Z make?'),
      answer: ['zzz'], distractors: ['sss', 'jeh', 'chuh']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es14 – Short a Words (10 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei132', skillId: 'es14', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: 🐱 (a furry pet that says meow)'),
      answer: ['c', 'a', 't'], distractors: ['b', 'o', 'e']),
  Item(id: 'ei133', skillId: 'es14', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: 🦇 (a flying animal that comes out at night)'),
      answer: ['b', 'a', 't'], distractors: ['c', 'o', 'u']),
  Item(id: 'ei134', skillId: 'es14', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: a soft cover you sleep under'),
      answer: ['m', 'a', 't'], distractors: ['c', 'o', 'e']),
  Item(id: 'ei135', skillId: 'es14', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: 🎩 (you wear it on your head)'),
      answer: ['h', 'a', 't'], distractors: ['c', 'o', 'b']),
  Item(id: 'ei136', skillId: 'es14', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: 🐀 (a small animal with a long tail)'),
      answer: ['r', 'a', 't'], distractors: ['c', 'o', 'b']),
  Item(id: 'ei137', skillId: 'es14', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a flat piece of paper showing a place"?'),
      answer: ['map'], distractors: ['cap', 'tap', 'nap']),
  Item(id: 'ei138', skillId: 'es14', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a covering for your head"?'),
      answer: ['cap'], distractors: ['map', 'cup', 'cop']),
  Item(id: 'ei139', skillId: 'es14', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "your father"?'),
      answer: ['dad'], distractors: ['did', 'dud', 'dog']),
  Item(id: 'ei140', skillId: 'es14', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: something that blows air'),
      answer: ['f', 'a', 'n'], distractors: ['p', 'o', 'u']),
  Item(id: 'ei141', skillId: 'es14', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a sweet fruit spread"?'),
      answer: ['jam'], distractors: ['gum', 'yam', 'ram']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es15 – Short e Words (10 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei142', skillId: 'es15', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: 🐔 (a female chicken)'),
      answer: ['h', 'e', 'n'], distractors: ['p', 'a', 'o']),
  Item(id: 'ei143', skillId: 'es15', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: something you write with'),
      answer: ['p', 'e', 'n'], distractors: ['b', 'a', 'o']),
  Item(id: 'ei144', skillId: 'es15', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "the number after nine"?'),
      answer: ['ten'], distractors: ['tan', 'tin', 'ton']),
  Item(id: 'ei145', skillId: 'es15', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "more than one man"?'),
      answer: ['men'], distractors: ['man', 'min', 'mon']),
  Item(id: 'ei146', skillId: 'es15', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: where you sleep at night'),
      answer: ['b', 'e', 'd'], distractors: ['p', 'a', 'o']),
  Item(id: 'ei147', skillId: 'es15', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word is a colour like fire and roses?'),
      answer: ['red'], distractors: ['rod', 'rid', 'rad']),
  Item(id: 'ei148', skillId: 'es15', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "your lower limb"?'),
      answer: ['leg'], distractors: ['log', 'lag', 'lig']),
  Item(id: 'ei149', skillId: 'es15', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "not dry"?'),
      answer: ['wet'], distractors: ['wit', 'wat', 'wot']),
  Item(id: 'ei150', skillId: 'es15', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: something used to catch fish or butterflies'),
      answer: ['n', 'e', 't'], distractors: ['p', 'a', 'o']),
  Item(id: 'ei151', skillId: 'es15', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to place something down"?'),
      answer: ['set'], distractors: ['sat', 'sit', 'sut']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es16 – Short i Words (10 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei152', skillId: 'es16', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: 🐷 (a pink farm animal)'),
      answer: ['p', 'i', 'g'], distractors: ['b', 'e', 'o']),
  Item(id: 'ei153', skillId: 'es16', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "very large"?'),
      answer: ['big'], distractors: ['beg', 'bag', 'bog']),
  Item(id: 'ei154', skillId: 'es16', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to make a hole in the ground"?'),
      answer: ['dig'], distractors: ['dog', 'dug', 'dag']),
  Item(id: 'ei155', skillId: 'es16', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word is a sweet fruit from a tree?'),
      answer: ['fig'], distractors: ['fog', 'fag', 'fug']),
  Item(id: 'ei156', skillId: 'es16', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: a small sharp object used to hold things together'),
      answer: ['p', 'i', 'n'], distractors: ['b', 'e', 'o']),
  Item(id: 'ei157', skillId: 'es16', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a metal container"?'),
      answer: ['tin'], distractors: ['tan', 'ten', 'ton']),
  Item(id: 'ei158', skillId: 'es16', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to be victorious"?'),
      answer: ['win'], distractors: ['wen', 'wan', 'won']),
  Item(id: 'ei159', skillId: 'es16', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to rest on a chair"?'),
      answer: ['sit'], distractors: ['set', 'sat', 'sut']),
  Item(id: 'ei160', skillId: 'es16', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to strike with your hand"?'),
      answer: ['hit'], distractors: ['hot', 'hat', 'hut']),
  Item(id: 'ei161', skillId: 'es16', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "the edge of your mouth"?'),
      answer: ['lip'], distractors: ['lap', 'lep', 'lop']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es17 – Short o Words (10 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei162', skillId: 'es17', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: 🐶 (a loyal pet that barks)'),
      answer: ['d', 'o', 'g'], distractors: ['b', 'a', 'e']),
  Item(id: 'ei163', skillId: 'es17', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: a piece of wood from a tree'),
      answer: ['l', 'o', 'g'], distractors: ['b', 'a', 'e']),
  Item(id: 'ei164', skillId: 'es17', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "thick mist"?'),
      answer: ['fog'], distractors: ['fig', 'fag', 'fug']),
  Item(id: 'ei165', skillId: 'es17', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a pig"?'),
      answer: ['hog'], distractors: ['hag', 'hig', 'hug']),
  Item(id: 'ei166', skillId: 'es17', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: a container you put things in'),
      answer: ['b', 'o', 'x'], distractors: ['p', 'a', 'e']),
  Item(id: 'ei167', skillId: 'es17', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a clever wild animal"?'),
      answer: ['fox'], distractors: ['fix', 'fax', 'fux']),
  Item(id: 'ei168', skillId: 'es17', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a container for cooking"?'),
      answer: ['pot'], distractors: ['pat', 'pet', 'put']),
  Item(id: 'ei169', skillId: 'es17', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "very warm"?'),
      answer: ['hot'], distractors: ['hat', 'hit', 'hut']),
  Item(id: 'ei170', skillId: 'es17', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "the highest point"?'),
      answer: ['top'], distractors: ['tap', 'tip', 'tup']),
  Item(id: 'ei171', skillId: 'es17', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: something used to clean the floor'),
      answer: ['m', 'o', 'p'], distractors: ['b', 'a', 'e']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es18 – Short u Words (10 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei172', skillId: 'es18', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: 🐛 (a small crawling insect)'),
      answer: ['b', 'u', 'g'], distractors: ['p', 'a', 'o']),
  Item(id: 'ei173', skillId: 'es18', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: a cup used for drinking tea'),
      answer: ['m', 'u', 'g'], distractors: ['p', 'a', 'o']),
  Item(id: 'ei174', skillId: 'es18', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to hold someone tightly"?'),
      answer: ['hug'], distractors: ['hog', 'hag', 'hig']),
  Item(id: 'ei175', skillId: 'es18', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a soft floor covering"?'),
      answer: ['rug'], distractors: ['rag', 'rig', 'rog']),
  Item(id: 'ei176', skillId: 'es18', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: the bright star in the sky'),
      answer: ['s', 'u', 'n'], distractors: ['p', 'a', 'o']),
  Item(id: 'ei177', skillId: 'es18', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "joy and enjoyment"?'),
      answer: ['fun'], distractors: ['fan', 'fen', 'fin']),
  Item(id: 'ei178', skillId: 'es18', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to move quickly on your feet"?'),
      answer: ['run'], distractors: ['ran', 'ren', 'rin']),
  Item(id: 'ei179', skillId: 'es18', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: a small container for drinking'),
      answer: ['c', 'u', 'p'], distractors: ['b', 'a', 'o']),
  Item(id: 'ei180', skillId: 'es18', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a large vehicle for carrying people"?'),
      answer: ['bus'], distractors: ['bas', 'bes', 'bis']),
  Item(id: 'ei181', skillId: 'es18', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a hard fruit with a shell"?'),
      answer: ['nut'], distractors: ['nat', 'net', 'not']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es19 – Magic e - Long a (8 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei182', skillId: 'es19', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: 🎂 (a sweet dessert for birthdays)'),
      answer: ['c', 'a', 'k', 'e'], distractors: ['p', 'o', 'u']),
  Item(id: 'ei183', skillId: 'es19', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a body of water"?'),
      answer: ['lake'], distractors: ['lack', 'lick', 'lock']),
  Item(id: 'ei184', skillId: 'es19', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to create or build something"?'),
      answer: ['make'], distractors: ['mack', 'mike', 'mock']),
  Item(id: 'ei185', skillId: 'es19', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "what someone is called"?'),
      answer: ['name'], distractors: ['nail', 'numb', 'nook']),
  Item(id: 'ei186', skillId: 'es19', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "an activity done for fun"?'),
      answer: ['game'], distractors: ['gape', 'gap', 'gem']),
  Item(id: 'ei187', skillId: 'es19', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "identical or equal"?'),
      answer: ['same'], distractors: ['some', 'came', 'sale']),
  Item(id: 'ei188', skillId: 'es19', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a long cloth worn over shoulders"?'),
      answer: ['cape'], distractors: ['cap', 'tape', 'cope']),
  Item(id: 'ei189', skillId: 'es19', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: a sticky strip used to stick things'),
      answer: ['t', 'a', 'p', 'e'], distractors: ['b', 'o', 'u']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es20 – Magic e - Long i (8 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei190', skillId: 'es20', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: 🚲 (a two-wheeled vehicle)'),
      answer: ['b', 'i', 'k', 'e'], distractors: ['p', 'a', 'o']),
  Item(id: 'ei191', skillId: 'es20', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to enjoy or find pleasant"?'),
      answer: ['like'], distractors: ['lick', 'lake', 'luck']),
  Item(id: 'ei192', skillId: 'es20', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to sit on something"?'),
      answer: ['ride'], distractors: ['ripe', 'rid', 'rice']),
  Item(id: 'ei193', skillId: 'es20', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "the edge or border"?'),
      answer: ['side'], distractors: ['sick', 'said', 'sad']),
  Item(id: 'ei194', skillId: 'es20', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "hours and minutes"?'),
      answer: ['time'], distractors: ['tim', 'team', 'tame']),
  Item(id: 'ei195', skillId: 'es20', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: a toy that flies in the wind'),
      answer: ['k', 'i', 't', 'e'], distractors: ['p', 'a', 'o']),
  Item(id: 'ei196', skillId: 'es20', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "belonging to me"?'),
      answer: ['mine'], distractors: ['mind', 'mint', 'mile']),
  Item(id: 'ei197', skillId: 'es20', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "the number after four"?'),
      answer: ['five'], distractors: ['give', 'hive', 'dive']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es21 – Magic e - Long o (8 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei198', skillId: 'es21', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "the place where you live"?'),
      answer: ['home'], distractors: ['hose', 'hone', 'come']),
  Item(id: 'ei199', skillId: 'es21', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a hard part of your body"?'),
      answer: ['bone'], distractors: ['done', 'gone', 'cone']),
  Item(id: 'ei200', skillId: 'es21', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: a long thick string'),
      answer: ['r', 'o', 'p', 'e'], distractors: ['b', 'a', 'u']),
  Item(id: 'ei201', skillId: 'es21', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a short message"?'),
      answer: ['note'], distractors: ['knot', 'not', 'nose']),
  Item(id: 'ei202', skillId: 'es21', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "an opening in the ground"?'),
      answer: ['hole'], distractors: ['hose', 'pole', 'hold']),
  Item(id: 'ei203', skillId: 'es21', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a long piece of wood"?'),
      answer: ['pole'], distractors: ['hole', 'pale', 'role']),
  Item(id: 'ei204', skillId: 'es21', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "the part on your face you smell with"?'),
      answer: ['nose'], distractors: ['hose', 'note', 'pose']),
  Item(id: 'ei205', skillId: 'es21', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a beautiful flower"?'),
      answer: ['rose'], distractors: ['nose', 'role', 'rope']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es22 – Magic e - Long u (8 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei206', skillId: 'es22', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "adorable or charming"?'),
      answer: ['cute'], distractors: ['cut', 'coat', 'city']),
  Item(id: 'ei207', skillId: 'es22', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "silent or quiet"?'),
      answer: ['mute'], distractors: ['mule', 'mud', 'mile']),
  Item(id: 'ei208', skillId: 'es22', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: a long round pipe'),
      answer: ['t', 'u', 'b', 'e'], distractors: ['p', 'a', 'o']),
  Item(id: 'ei209', skillId: 'es22', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a piece of music"?'),
      answer: ['tune'], distractors: ['town', 'tone', 'turn']),
  Item(id: 'ei210', skillId: 'es22', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a guide or guideline"?'),
      answer: ['rule'], distractors: ['ruler', 'role', 'rude']),
  Item(id: 'ei211', skillId: 'es22', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to make use of something"?'),
      answer: ['use'], distractors: ['us', 'due', 'cue']),
  Item(id: 'ei212', skillId: 'es22', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: a 3D shape with six square faces'),
      answer: ['c', 'u', 'b', 'e'], distractors: ['p', 'a', 'o']),
  Item(id: 'ei213', skillId: 'es22', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a casual way to address a man"?'),
      answer: ['dude'], distractors: ['due', 'deed', 'dull']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es23 – L-Blends (bl, cl, fl, gl) (8 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei214', skillId: 'es23', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "the colour of the sky"?'),
      answer: ['blue'], distractors: ['bell', 'ball', 'bile']),
  Item(id: 'ei215', skillId: 'es23', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: to hit your hands together'),
      answer: ['c', 'l', 'a', 'p'], distractors: ['b', 'o', 'u']),
  Item(id: 'ei216', skillId: 'es23', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a piece of cloth on a pole"?'),
      answer: ['flag'], distractors: ['flat', 'flog', 'fled']),
  Item(id: 'ei217', skillId: 'es23', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a drinking container"?'),
      answer: ['glass'], distractors: ['glad', 'gloss', 'grass']),
  Item(id: 'ei218', skillId: 'es23', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a toy brick"?'),
      answer: ['block'], distractors: ['black', 'clock', 'blame']),
  Item(id: 'ei219', skillId: 'es23', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a device that tells time"?'),
      answer: ['clock'], distractors: ['click', 'cluck', 'block']),
  Item(id: 'ei220', skillId: 'es23', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to move through the air"?'),
      answer: ['fly'], distractors: ['fry', 'flag', 'flow']),
  Item(id: 'ei221', skillId: 'es23', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "happy and pleased"?'),
      answer: ['glad'], distractors: ['gold', 'flag', 'glass']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es24 – R-Blends (br, cr, dr, fr, gr) (8 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei222', skillId: 'es24', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a colour like chocolate"?'),
      answer: ['brown'], distractors: ['born', 'bran', 'brow']),
  Item(id: 'ei223', skillId: 'es24', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: a sea creature with claws'),
      answer: ['c', 'r', 'a', 'b'], distractors: ['p', 'o', 'u']),
  Item(id: 'ei224', skillId: 'es24', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a musical instrument you hit"?'),
      answer: ['drum'], distractors: ['drain', 'drop', 'draw']),
  Item(id: 'ei225', skillId: 'es24', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: 🐸 (a green animal that hops)'),
      answer: ['f', 'r', 'o', 'g'], distractors: ['b', 'a', 'u']),
  Item(id: 'ei226', skillId: 'es24', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "the colour of grass"?'),
      answer: ['green'], distractors: ['grain', 'grin', 'great']),
  Item(id: 'ei227', skillId: 'es24', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to shout or weep"?'),
      answer: ['cry'], distractors: ['dry', 'try', 'fry']),
  Item(id: 'ei228', skillId: 'es24', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "not wet"?'),
      answer: ['dry'], distractors: ['cry', 'fry', 'try']),
  Item(id: 'ei229', skillId: 'es24', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "new and clean"?'),
      answer: ['fresh'], distractors: ['flash', 'flesh', 'crash']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es25 – S-Blends (sk, sl, sm, sn, sp, st) (8 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei230', skillId: 'es25', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to jump or hop"?'),
      answer: ['skip'], distractors: ['skin', 'skim', 'slip']),
  Item(id: 'ei231', skillId: 'es25', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to rest in bed"?'),
      answer: ['sleep'], distractors: ['slip', 'slide', 'sheep']),
  Item(id: 'ei232', skillId: 'es25', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a happy expression on your face"?'),
      answer: ['smile'], distractors: ['small', 'smell', 'slime']),
  Item(id: 'ei233', skillId: 'es25', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: ❄️ (white flakes that fall in winter)'),
      answer: ['s', 'n', 'o', 'w'], distractors: ['p', 'a', 'u']),
  Item(id: 'ei234', skillId: 'es25', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to turn around quickly"?'),
      answer: ['spin'], distractors: ['skin', 'span', 'snap']),
  Item(id: 'ei235', skillId: 'es25', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: ⭐ (a bright light in the night sky)'),
      answer: ['s', 't', 'a', 'r'], distractors: ['p', 'o', 'u']),
  Item(id: 'ei236', skillId: 'es25', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to move in water"?'),
      answer: ['swim'], distractors: ['skin', 'stem', 'slim']),
  Item(id: 'ei237', skillId: 'es25', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to cease or halt"?'),
      answer: ['stop'], distractors: ['step', 'slap', 'stamp']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es26 – Digraphs (sh, ch, th, wh) (12 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei238', skillId: 'es26', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a large boat"?'),
      answer: ['ship'], distractors: ['shop', 'slip', 'chip']),
  Item(id: 'ei239', skillId: 'es26', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a place where you buy things"?'),
      answer: ['shop'], distractors: ['ship', 'stop', 'chap']),
  Item(id: 'ei240', skillId: 'es26', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "what you wear on your foot"?'),
      answer: ['shoe'], distractors: ['show', 'shop', 'ship']),
  Item(id: 'ei241', skillId: 'es26', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to talk informally"?'),
      answer: ['chat'], distractors: ['cat', 'chin', 'chip']),
  Item(id: 'ei242', skillId: 'es26', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "the part below your nose"?'),
      answer: ['chin'], distractors: ['chain', 'chat', 'thin']),
  Item(id: 'ei243', skillId: 'es26', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: a small piece of something'),
      answer: ['c', 'h', 'i', 'p'], distractors: ['b', 'o', 'u']),
  Item(id: 'ei244', skillId: 'es26', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "not thick"?'),
      answer: ['thin'], distractors: ['chin', 'then', 'than']),
  Item(id: 'ei245', skillId: 'es26', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "pointing to something"?'),
      answer: ['that'], distractors: ['than', 'thin', 'this']),
  Item(id: 'ei246', skillId: 'es26', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "referring to something nearby"?'),
      answer: ['this'], distractors: ['that', 'thin', 'thus']),
  Item(id: 'ei247', skillId: 'es26', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "at what time"?'),
      answer: ['when'], distractors: ['then', 'went', 'whom']),
  Item(id: 'ei248', skillId: 'es26', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "asking about something"?'),
      answer: ['what'], distractors: ['when', 'whom', 'that']),
  Item(id: 'ei249', skillId: 'es26', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell the word: 🐋 (a very large sea animal)'),
      answer: ['w', 'h', 'a', 'l', 'e'], distractors: ['b', 'o', 'u']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es27 – Dolch Pre-Primer (10 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei250', skillId: 'es27', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word is used before a specific noun, like "___ sun"?'),
      answer: ['the'], distractors: ['a', 'an', 'is']),
  Item(id: 'ei251', skillId: 'es27', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "in the direction of"?'),
      answer: ['to'], distractors: ['do', 'go', 'so']),
  Item(id: 'ei252', skillId: 'es27', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "also or in addition"?'),
      answer: ['and'], distractors: ['end', 'any', 'ant']),
  Item(id: 'ei253', skillId: 'es27', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "one single thing"?'),
      answer: ['a'], distractors: ['an', 'the', 'at']),
  Item(id: 'ei254', skillId: 'es27', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "yourself, referring to oneself"?'),
      answer: ['I'], distractors: ['me', 'my', 'we']),
  Item(id: 'ei255', skillId: 'es27', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "exists or is"?'),
      answer: ['is'], distractors: ['it', 'as', 'us']),
  Item(id: 'ei256', skillId: 'es27', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word refers to a thing or object?'),
      answer: ['it'], distractors: ['is', 'in', 'at']),
  Item(id: 'ei257', skillId: 'es27', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word refers to the person being spoken to?'),
      answer: ['you'], distractors: ['your', 'yow', 'yet']),
  Item(id: 'ei258', skillId: 'es27', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "referring to something specific"?'),
      answer: ['that'], distractors: ['than', 'then', 'this']),
  Item(id: 'ei259', skillId: 'es27', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "inside or within"?'),
      answer: ['in'], distractors: ['on', 'at', 'up']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es28 – Dolch Primer (10 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei260', skillId: 'es28', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "everything or everyone"?'),
      answer: ['all'], distractors: ['ill', 'ale', 'eel']),
  Item(id: 'ei261', skillId: 'es28', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "I exist" (first person)?'),
      answer: ['am'], distractors: ['an', 'at', 'as']),
  Item(id: 'ei262', skillId: 'es28', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "they exist" (plural)?'),
      answer: ['are'], distractors: ['art', 'arc', 'ate']),
  Item(id: 'ei263', skillId: 'es28', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "in a place or position"?'),
      answer: ['at'], distractors: ['it', 'in', 'on']),
  Item(id: 'ei264', skillId: 'es28', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "consumed food in the past"?'),
      answer: ['ate'], distractors: ['are', 'art', 'ant']),
  Item(id: 'ei265', skillId: 'es28', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to exist"?'),
      answer: ['be'], distractors: ['by', 'do', 'go']),
  Item(id: 'ei266', skillId: 'es28', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "however or except"?'),
      answer: ['but'], distractors: ['bat', 'bit', 'bet']),
  Item(id: 'ei267', skillId: 'es28', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "arrived or moved towards"?'),
      answer: ['came'], distractors: ['come', 'calm', 'care']),
  Item(id: 'ei268', skillId: 'es28', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "performed an action in the past"?'),
      answer: ['did'], distractors: ['hid', 'kid', 'bid']),
  Item(id: 'ei269', skillId: 'es28', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to perform an action"?'),
      answer: ['do'], distractors: ['to', 'go', 'so']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es29 – Common Words (10 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei270', skillId: 'es29', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "spoke words"?'),
      answer: ['said'], distractors: ['laid', 'paid', 'made']),
  Item(id: 'ei271', skillId: 'es29', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "possesses (he/she/it)"?'),
      answer: ['has'], distractors: ['his', 'was', 'had']),
  Item(id: 'ei272', skillId: 'es29', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "to possess"?'),
      answer: ['have'], distractors: ['give', 'halve', 'save']),
  Item(id: 'ei273', skillId: 'es29', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "starting from a place"?'),
      answer: ['from'], distractors: ['form', 'room', 'farm']),
  Item(id: 'ei274', skillId: 'es29', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word refers to "a group of people or things"?'),
      answer: ['they'], distractors: ['them', 'then', 'there']),
  Item(id: 'ei275', skillId: 'es29', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "existed in the past"?'),
      answer: ['been'], distractors: ['bean', 'seen', 'keen']),
  Item(id: 'ei276', skillId: 'es29', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "together with"?'),
      answer: ['with'], distractors: ['wish', 'will', 'which']),
  Item(id: 'ei277', skillId: 'es29', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "a large number"?'),
      answer: ['many'], distractors: ['man', 'main', 'mainly']),
  Item(id: 'ei278', skillId: 'es29', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "an unspecified amount"?'),
      answer: ['some'], distractors: ['same', 'come', 'home']),
  Item(id: 'ei279', skillId: 'es29', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word means "the number one"?'),
      answer: ['one'], distractors: ['won', 'own', 'once']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es30 – Fill in the Blanks (10 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei280', skillId: 'es30', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Fill in the blank: c_t (a furry pet)'),
      answer: ['cat'], distractors: ['cut', 'cot', 'cit']),
  Item(id: 'ei281', skillId: 'es30', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Fill in the blank: d_g (a pet that barks)'),
      answer: ['dog'], distractors: ['dig', 'dug', 'dag']),
  Item(id: 'ei282', skillId: 'es30', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Fill in the blank: s_n (the bright star in the sky)'),
      answer: ['sun'], distractors: ['son', 'sin', 'san']),
  Item(id: 'ei283', skillId: 'es30', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Fill in the blank: b_d (where you sleep)'),
      answer: ['bed'], distractors: ['bad', 'bid', 'bud']),
  Item(id: 'ei284', skillId: 'es30', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Fill in the blank: h_t (worn on the head)'),
      answer: ['hat'], distractors: ['hot', 'hit', 'hut']),
  Item(id: 'ei285', skillId: 'es30', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Fill in the blank: p_g (a pink farm animal)'),
      answer: ['pig'], distractors: ['peg', 'pug', 'pag']),
  Item(id: 'ei286', skillId: 'es30', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Fill in the blank: b_x (a container)'),
      answer: ['box'], distractors: ['bex', 'bix', 'bax']),
  Item(id: 'ei287', skillId: 'es30', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Fill in the blank: m_p (a picture showing places)'),
      answer: ['map'], distractors: ['mop', 'mup', 'mip']),
  Item(id: 'ei288', skillId: 'es30', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Fill in the blank: f_x (a clever wild animal)'),
      answer: ['fox'], distractors: ['fix', 'fax', 'fux']),
  Item(id: 'ei289', skillId: 'es30', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Fill in the blank: c_p (a small drinking container)'),
      answer: ['cup'], distractors: ['cap', 'cop', 'cep']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es31 – Spelling from Picture (8 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei290', skillId: 'es31', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🐱 (a furry pet)'),
      answer: ['c', 'a', 't'], distractors: ['b', 'o', 'e']),
  Item(id: 'ei291', skillId: 'es31', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🐶 (a loyal pet)'),
      answer: ['d', 'o', 'g'], distractors: ['b', 'a', 'e']),
  Item(id: 'ei292', skillId: 'es31', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: ☀️ (the bright star)'),
      answer: ['s', 'u', 'n'], distractors: ['p', 'a', 'o']),
  Item(id: 'ei293', skillId: 'es31', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🐷 (a pink farm animal)'),
      answer: ['p', 'i', 'g'], distractors: ['b', 'e', 'o']),
  Item(id: 'ei294', skillId: 'es31', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🎩 (worn on the head)'),
      answer: ['h', 'a', 't'], distractors: ['c', 'o', 'b']),
  Item(id: 'ei295', skillId: 'es31', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🐔 (a female chicken)'),
      answer: ['h', 'e', 'n'], distractors: ['p', 'a', 'o']),
  Item(id: 'ei296', skillId: 'es31', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🦇 (a flying night animal)'),
      answer: ['b', 'a', 't'], distractors: ['c', 'o', 'u']),
  Item(id: 'ei297', skillId: 'es31', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🐛 (a small insect)'),
      answer: ['b', 'u', 'g'], distractors: ['p', 'a', 'o']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es32 – Rhyming Words (8 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei298', skillId: 'es32', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word rhymes with "cat"?'),
      answer: ['hat'], distractors: ['hot', 'hit', 'hut']),
  Item(id: 'ei299', skillId: 'es32', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word rhymes with "dog"?'),
      answer: ['log'], distractors: ['leg', 'lag', 'lug']),
  Item(id: 'ei300', skillId: 'es32', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word rhymes with "sun"?'),
      answer: ['fun'], distractors: ['fan', 'fen', 'fin']),
  Item(id: 'ei301', skillId: 'es32', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word rhymes with "bed"?'),
      answer: ['red'], distractors: ['rod', 'rid', 'rad']),
  Item(id: 'ei302', skillId: 'es32', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word rhymes with "pig"?'),
      answer: ['big'], distractors: ['beg', 'bag', 'bog']),
  Item(id: 'ei303', skillId: 'es32', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word rhymes with "cake"?'),
      answer: ['lake'], distractors: ['lack', 'luck', 'lock']),
  Item(id: 'ei304', skillId: 'es32', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word rhymes with "hot"?'),
      answer: ['pot'], distractors: ['pet', 'pat', 'put']),
  Item(id: 'ei305', skillId: 'es32', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which word rhymes with "bike"?'),
      answer: ['like'], distractors: ['lick', 'lake', 'lock']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es33 – Articles (a, an, the) (8 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei306', skillId: 'es33', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Fill in: ___ elephant'),
      answer: ['an'], distractors: ['a', 'the', 'is']),
  Item(id: 'ei307', skillId: 'es33', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Fill in: ___ cat'),
      answer: ['a'], distractors: ['an', 'the', 'is']),
  Item(id: 'ei308', skillId: 'es33', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Fill in: ___ sun rises in the east'),
      answer: ['The'], distractors: ['A', 'An', 'Is']),
  Item(id: 'ei309', skillId: 'es33', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Fill in: ___ apple a day keeps the doctor away'),
      answer: ['An'], distractors: ['A', 'The', 'Is']),
  Item(id: 'ei310', skillId: 'es33', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Fill in: ___ umbrella'),
      answer: ['an'], distractors: ['a', 'the', 'is']),
  Item(id: 'ei311', skillId: 'es33', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Fill in: ___ dog is barking'),
      answer: ['The'], distractors: ['A', 'An', 'Is']),
  Item(id: 'ei312', skillId: 'es33', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Fill in: ___ book'),
      answer: ['a'], distractors: ['an', 'the', 'is']),
  Item(id: 'ei313', skillId: 'es33', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Fill in: ___ ice cream'),
      answer: ['an'], distractors: ['a', 'the', 'is']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es34 – Plurals (8 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei314', skillId: 'es34', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What is the plural of "cat"?'),
      answer: ['cats'], distractors: ['cat', 'cates', 'catis']),
  Item(id: 'ei315', skillId: 'es34', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What is the plural of "box"?'),
      answer: ['boxes'], distractors: ['boxs', 'box', 'boxen']),
  Item(id: 'ei316', skillId: 'es34', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What is the plural of "dog"?'),
      answer: ['dogs'], distractors: ['dog', 'doges', 'dogen']),
  Item(id: 'ei317', skillId: 'es34', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What is the plural of "baby"?'),
      answer: ['babies'], distractors: ['babys', 'baby', 'babis']),
  Item(id: 'ei318', skillId: 'es34', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What is the plural of "bus"?'),
      answer: ['buses'], distractors: ['buss', 'bus', 'busen']),
  Item(id: 'ei319', skillId: 'es34', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What is the plural of "child"?'),
      answer: ['children'], distractors: ['childs', 'child', 'childes']),
  Item(id: 'ei320', skillId: 'es34', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What is the plural of "fish"?'),
      answer: ['fish'], distractors: ['fishes', 'fishs', 'fishen']),
  Item(id: 'ei321', skillId: 'es34', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What is the plural of "leaf"?'),
      answer: ['leaves'], distractors: ['leafs', 'leaf', 'leafes']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es35 – Build a Sentence (6 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei322', skillId: 'es35', exerciseType: ExerciseType.build_sentence,
      prompt: ItemPrompt(text: 'Arrange the words to make a sentence: cat, The, sat'),
      answer: ['The', 'cat', 'sat'], distractors: ['mat', 'on']),
  Item(id: 'ei323', skillId: 'es35', exerciseType: ExerciseType.build_sentence,
      prompt: ItemPrompt(text: 'Arrange the words to make a sentence: big, is, The, dog'),
      answer: ['The', 'dog', 'is', 'big'], distractors: ['cat', 'and']),
  Item(id: 'ei324', skillId: 'es35', exerciseType: ExerciseType.build_sentence,
      prompt: ItemPrompt(text: 'Arrange the words to make a sentence: like, I, cake'),
      answer: ['I', 'like', 'cake'], distractors: ['we', 'eat']),
  Item(id: 'ei325', skillId: 'es35', exerciseType: ExerciseType.build_sentence,
      prompt: ItemPrompt(text: 'Arrange the words to make a sentence: to, We, go, school'),
      answer: ['We', 'go', 'to', 'school'], distractors: ['they', 'the']),
  Item(id: 'ei326', skillId: 'es35', exerciseType: ExerciseType.build_sentence,
      prompt: ItemPrompt(text: 'Arrange the words to make a sentence: is, The, red, apple'),
      answer: ['The', 'apple', 'is', 'red'], distractors: ['green', 'a']),
  Item(id: 'ei327', skillId: 'es35', exerciseType: ExerciseType.build_sentence,
      prompt: ItemPrompt(text: 'Arrange the words to make a sentence: plays, She, the, park, in'),
      answer: ['She', 'plays', 'in', 'the', 'park'], distractors: ['he', 'at']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es36 – Opposites (8 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei328', skillId: 'es36', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What is the opposite of "big"?'),
      answer: ['small'], distractors: ['tall', 'long', 'wide']),
  Item(id: 'ei329', skillId: 'es36', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What is the opposite of "hot"?'),
      answer: ['cold'], distractors: ['cool', 'warm', 'wet']),
  Item(id: 'ei330', skillId: 'es36', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What is the opposite of "tall"?'),
      answer: ['short'], distractors: ['small', 'tiny', 'low']),
  Item(id: 'ei331', skillId: 'es36', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What is the opposite of "fast"?'),
      answer: ['slow'], distractors: ['stop', 'late', 'quick']),
  Item(id: 'ei332', skillId: 'es36', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What is the opposite of "up"?'),
      answer: ['down'], distractors: ['low', 'under', 'below']),
  Item(id: 'ei333', skillId: 'es36', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What is the opposite of "happy"?'),
      answer: ['sad'], distractors: ['mad', 'bad', 'angry']),
  Item(id: 'ei334', skillId: 'es36', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What is the opposite of "day"?'),
      answer: ['night'], distractors: ['dark', 'evening', 'sleep']),
  Item(id: 'ei335', skillId: 'es36', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What is the opposite of "old"?'),
      answer: ['new'], distractors: ['young', 'fresh', 'early']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es37 – Short Stories (6 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei336', skillId: 'es37', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Read: "The cat sat on the mat. The cat is happy." Where did the cat sit?'),
      answer: ['on the mat'], distractors: ['on the bed', 'on the chair', 'on the table']),
  Item(id: 'ei337', skillId: 'es37', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Read: "Ravi has a red ball. He plays with it in the park." What colour is the ball?'),
      answer: ['red'], distractors: ['blue', 'green', 'yellow']),
  Item(id: 'ei338', skillId: 'es37', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Read: "The sun is hot today. Mina wears a hat." Why does Mina wear a hat?'),
      answer: ['because the sun is hot'], distractors: ['because it is cold', 'because it is raining', 'because she likes hats']),
  Item(id: 'ei339', skillId: 'es37', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Read: "The dog ran fast. It caught the ball." What did the dog catch?'),
      answer: ['the ball'], distractors: ['a cat', 'a stick', 'a bone']),
  Item(id: 'ei340', skillId: 'es37', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Read: "An ant is small but strong. It can carry big things." What can the ant carry?'),
      answer: ['big things'], distractors: ['small things', 'nothing', 'only food']),
  Item(id: 'ei341', skillId: 'es37', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Read: "Meera likes to read books. She reads every night." When does Meera read?'),
      answer: ['every night'], distractors: ['every morning', 'every afternoon', 'sometimes']),

  // ═══════════════════════════════════════════════════════════════════════════
  // es38 – Sequencing (6 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei342', skillId: 'es38', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What happens FIRST when you brush your teeth?'),
      answer: ['pick up the toothbrush'], distractors: ['rinse your mouth', 'put toothpaste on', 'brush your teeth']),
  Item(id: 'ei343', skillId: 'es38', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What happens LAST when you eat breakfast?'),
      answer: ['wash your plate'], distractors: ['pour the milk', 'eat the food', 'sit at the table']),
  Item(id: 'ei344', skillId: 'es38', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What comes NEXT: First you wake up, then you ___?'),
      answer: ['get out of bed'], distractors: ['go to sleep', 'eat lunch', 'go to school']),
  Item(id: 'ei345', skillId: 'es38', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What happens FIRST when it rains?'),
      answer: ['clouds gather in the sky'], distractors: ['you open an umbrella', 'puddles form', 'the sun shines']),
  Item(id: 'ei346', skillId: 'es38', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What happens LAST in a story about planting a seed?'),
      answer: ['a plant grows'], distractors: ['dig a hole', 'put the seed in', 'water the soil']),
  Item(id: 'ei347', skillId: 'es38', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Put in order: What comes AFTER "put on shoes"?'),
      answer: ['tie the laces'], distractors: ['take them off', 'put on socks', 'buy new shoes']),

  // ═══════════════════════════════════════════════════════════════════════════
  // E9 – Vocabulary & Spelling (es39-es41)
  // E10 – Singular, Plural & Matching (es42-es45)
  // E11 – Sentence Building & More (es46-es49)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'ei348', skillId: 'es39', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Complete the word: c_t (animal)"),
      answer: ['cat'], distractors: ['cot', 'cut', 'cit']),
  Item(id: 'ei349', skillId: 'es39', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Complete the word: d_g (animal)"),
      answer: ['dog'], distractors: ['dig', 'dug', 'dag']),
  Item(id: 'ei350', skillId: 'es39', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Complete the word: b__k (to read)"),
      answer: ['book'], distractors: ['bark', 'bank', 'bunk']),
  Item(id: 'ei351', skillId: 'es39', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Complete the word: s_n (in the sky)"),
      answer: ['sun'], distractors: ['son', 'sin', 'san']),
  Item(id: 'ei352', skillId: 'es39', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Complete the word: f__h (swims)"),
      answer: ['fish'], distractors: ['fash', 'fush', 'fosh']),
  Item(id: 'ei353', skillId: 'es39', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Complete the word: tr_e (tall plant)"),
      answer: ['tree'], distractors: ['true', 'free', 'tire']),
  Item(id: 'ei354', skillId: 'es39', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Complete the word: sch_ol"),
      answer: ['school'], distractors: ['schcol', 'schoel', 'schoal']),
  Item(id: 'ei355', skillId: 'es39', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Complete the word: app_e (fruit)"),
      answer: ['apple'], distractors: ['apper', 'apply', 'appel']),
  Item(id: 'ei356', skillId: 'es39', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Complete the word: wat_r (you drink it)"),
      answer: ['water'], distractors: ['wator', 'watar', 'witer']),
  Item(id: 'ei357', skillId: 'es39', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Complete the word: h_use (you live in)"),
      answer: ['house'], distractors: ['hause', 'hurse', 'hause']),
  Item(id: 'ei358', skillId: 'es39', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Complete the word: f_ower (in garden)"),
      answer: ['flower'], distractors: ['flawer', 'flewer', 'flour']),
  Item(id: 'ei359', skillId: 'es39', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Complete the word: t_acher (in school)"),
      answer: ['teacher'], distractors: ['teecher', 'tacher', 'ticher']),
  Item(id: 'ei360', skillId: 'es40', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which is the correct spelling?"),
      answer: ['banana'], distractors: ['bannana', 'bananna', 'banena']),
  Item(id: 'ei361', skillId: 'es40', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which is the correct spelling?"),
      answer: ['elephant'], distractors: ['elaphant', 'elefant', 'eliphant']),
  Item(id: 'ei362', skillId: 'es40', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which is the correct spelling?"),
      answer: ['rabbit'], distractors: ['rabit', 'rabbitt', 'rabitt']),
  Item(id: 'ei363', skillId: 'es40', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which is the correct spelling?"),
      answer: ['kitchen'], distractors: ['kichen', 'kitchin', 'kichin']),
  Item(id: 'ei364', skillId: 'es40', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which is the correct spelling?"),
      answer: ['butterfly'], distractors: ['buttrfly', 'buterfly', 'buttrfli']),
  Item(id: 'ei365', skillId: 'es40', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which is the correct spelling?"),
      answer: ['umbrella'], distractors: ['umbrela', 'umbrealla', 'umbrela']),
  Item(id: 'ei366', skillId: 'es40', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which is the correct spelling?"),
      answer: ['brother'], distractors: ['brothr', 'brothar', 'brohter']),
  Item(id: 'ei367', skillId: 'es40', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which is the correct spelling?"),
      answer: ['chicken'], distractors: ['chiken', 'chickn', 'chikin']),
  Item(id: 'ei368', skillId: 'es40', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which is the correct spelling?"),
      answer: ['orange'], distractors: ['orenge', 'orang', 'ornge']),
  Item(id: 'ei369', skillId: 'es40', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which is the correct spelling?"),
      answer: ['pencil'], distractors: ['pensil', 'pencl', 'pencle']),
  Item(id: 'ei370', skillId: 'es40', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which is the correct spelling?"),
      answer: ['friend'], distractors: ['frend', 'freind', 'frind']),
  Item(id: 'ei371', skillId: 'es40', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which is the correct spelling?"),
      answer: ['happy'], distractors: ['hapy', 'hapyy', 'happee']),
  Item(id: 'ei372', skillId: 'es41', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What does 'enormous' mean?"),
      answer: ['very big'], distractors: ['very small', 'very fast', 'very cold']),
  Item(id: 'ei373', skillId: 'es41', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What does 'tiny' mean?"),
      answer: ['very small'], distractors: ['very big', 'very loud', 'very hot']),
  Item(id: 'ei374', skillId: 'es41', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What does 'delicious' mean?"),
      answer: ['tastes very good'], distractors: ['looks ugly', 'feels cold', 'sounds loud']),
  Item(id: 'ei375', skillId: 'es41', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What does 'brave' mean?"),
      answer: ['not scared'], distractors: ['very tired', 'very hungry', 'very sad']),
  Item(id: 'ei376', skillId: 'es41', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What does 'gentle' mean?"),
      answer: ['soft and kind'], distractors: ['hard and rough', 'loud and noisy', 'fast and wild']),
  Item(id: 'ei377', skillId: 'es41', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What does 'curious' mean?"),
      answer: ['wanting to know more'], distractors: ['feeling sleepy', 'feeling angry', 'feeling sad']),
  Item(id: 'ei378', skillId: 'es41', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What does 'swift' mean?"),
      answer: ['very fast'], distractors: ['very slow', 'very heavy', 'very big']),
  Item(id: 'ei379', skillId: 'es41', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What does 'bright' mean?"),
      answer: ['full of light'], distractors: ['full of dark', 'very cold', 'very wet']),
  Item(id: 'ei380', skillId: 'es41', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What does 'ancient' mean?"),
      answer: ['very old'], distractors: ['very new', 'very big', 'very small']),
  Item(id: 'ei381', skillId: 'es41', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What does 'cheerful' mean?"),
      answer: ['happy and smiling'], distractors: ['sad and crying', 'angry and mad', 'sleepy and tired']),
  Item(id: 'ei382', skillId: 'es42', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'cat'?"),
      answer: ['cats'], distractors: ['cates', 'caties', 'catis']),
  Item(id: 'ei383', skillId: 'es42', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'dog'?"),
      answer: ['dogs'], distractors: ['doges', 'dogies', 'doggies']),
  Item(id: 'ei384', skillId: 'es42', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'book'?"),
      answer: ['books'], distractors: ['bookes', 'bookies', 'bookis']),
  Item(id: 'ei385', skillId: 'es42', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'box'?"),
      answer: ['boxes'], distractors: ['boxs', 'boxies', 'boxxes']),
  Item(id: 'ei386', skillId: 'es42', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'bus'?"),
      answer: ['buses'], distractors: ['buss', 'busses', 'busies']),
  Item(id: 'ei387', skillId: 'es42', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'baby'?"),
      answer: ['babies'], distractors: ['babys', 'babyes', 'babees']),
  Item(id: 'ei388', skillId: 'es42', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'city'?"),
      answer: ['cities'], distractors: ['citys', 'cityes', 'citees']),
  Item(id: 'ei389', skillId: 'es42', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'dish'?"),
      answer: ['dishes'], distractors: ['dishs', 'dishies', 'dishis']),
  Item(id: 'ei390', skillId: 'es42', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'lady'?"),
      answer: ['ladies'], distractors: ['ladys', 'ladyes', 'ladees']),
  Item(id: 'ei391', skillId: 'es42', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'berry'?"),
      answer: ['berries'], distractors: ['berrys', 'berryes', 'berrees']),
  Item(id: 'ei392', skillId: 'es42', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'fox'?"),
      answer: ['foxes'], distractors: ['foxs', 'foxies', 'foxis']),
  Item(id: 'ei393', skillId: 'es42', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'story'?"),
      answer: ['stories'], distractors: ['storys', 'storyes', 'storees']),
  Item(id: 'ei394', skillId: 'es43', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'child'?"),
      answer: ['children'], distractors: ['childs', 'childes', 'childies']),
  Item(id: 'ei395', skillId: 'es43', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'mouse'?"),
      answer: ['mice'], distractors: ['mouses', 'mices', 'mousees']),
  Item(id: 'ei396', skillId: 'es43', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'foot'?"),
      answer: ['feet'], distractors: ['foots', 'footes', 'feets']),
  Item(id: 'ei397', skillId: 'es43', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'tooth'?"),
      answer: ['teeth'], distractors: ['tooths', 'toothes', 'teeths']),
  Item(id: 'ei398', skillId: 'es43', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'man'?"),
      answer: ['men'], distractors: ['mans', 'menes', 'manes']),
  Item(id: 'ei399', skillId: 'es43', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'woman'?"),
      answer: ['women'], distractors: ['womans', 'womens', 'womanes']),
  Item(id: 'ei400', skillId: 'es43', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'fish'?"),
      answer: ['fish'], distractors: ['fishes', 'fishs', 'fishies']),
  Item(id: 'ei401', skillId: 'es43', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'sheep'?"),
      answer: ['sheep'], distractors: ['sheeps', 'sheepes', 'shieps']),
  Item(id: 'ei402', skillId: 'es43', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'goose'?"),
      answer: ['geese'], distractors: ['gooses', 'goosies', 'geeses']),
  Item(id: 'ei403', skillId: 'es43', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "What is the plural of 'person'?"),
      answer: ['people'], distractors: ['persons', 'persones', 'peoples']),
  Item(id: 'ei404', skillId: 'es44', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Match: A place where you sleep"),
      answer: ['bedroom'], distractors: ['kitchen', 'bathroom', 'garden']),
  Item(id: 'ei405', skillId: 'es44', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Match: A place where you cook"),
      answer: ['kitchen'], distractors: ['bedroom', 'garden', 'bathroom']),
  Item(id: 'ei406', skillId: 'es44', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Match: Something you read"),
      answer: ['book'], distractors: ['chair', 'table', 'pencil']),
  Item(id: 'ei407', skillId: 'es44', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Match: Something you wear on your feet"),
      answer: ['shoes'], distractors: ['hat', 'gloves', 'scarf']),
  Item(id: 'ei408', skillId: 'es44', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Match: An animal that can fly"),
      answer: ['bird'], distractors: ['fish', 'snake', 'frog']),
  Item(id: 'ei409', skillId: 'es44', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Match: A fruit that is yellow"),
      answer: ['banana'], distractors: ['apple', 'grape', 'cherry']),
  Item(id: 'ei410', skillId: 'es44', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Match: Something you use to write"),
      answer: ['pencil'], distractors: ['eraser', 'ruler', 'scissors']),
  Item(id: 'ei411', skillId: 'es44', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Match: A vehicle with two wheels"),
      answer: ['bicycle'], distractors: ['car', 'bus', 'train']),
  Item(id: 'ei412', skillId: 'es44', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Match: A place where flowers grow"),
      answer: ['garden'], distractors: ['kitchen', 'bedroom', 'bathroom']),
  Item(id: 'ei413', skillId: 'es44', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Match: Something that tells the time"),
      answer: ['clock'], distractors: ['mirror', 'window', 'lamp']),
  Item(id: 'ei414', skillId: 'es45', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which one is a FRUIT?"),
      answer: ['apple'], distractors: ['car', 'chair', 'cat']),
  Item(id: 'ei415', skillId: 'es45', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which one is an ANIMAL?"),
      answer: ['elephant'], distractors: ['eraser', 'elevator', 'envelope']),
  Item(id: 'ei416', skillId: 'es45', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which one is a COLOR?"),
      answer: ['purple'], distractors: ['pencil', 'paper', 'plate']),
  Item(id: 'ei417', skillId: 'es45', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which one is CLOTHING?"),
      answer: ['shirt'], distractors: ['shoe polish', 'shelf', 'sheet']),
  Item(id: 'ei418', skillId: 'es45', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which one is a VEHICLE?"),
      answer: ['airplane'], distractors: ['ant', 'apple', 'anchor']),
  Item(id: 'ei419', skillId: 'es45', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which one is a BODY PART?"),
      answer: ['elbow'], distractors: ['engine', 'elephant', 'egg']),
  Item(id: 'ei420', skillId: 'es45', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which one is FURNITURE?"),
      answer: ['table'], distractors: ['tiger', 'tomato', 'towel']),
  Item(id: 'ei421', skillId: 'es45', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which one is FOOD?"),
      answer: ['sandwich'], distractors: ['sand', 'sandals', 'sandpaper']),
  Item(id: 'ei422', skillId: 'es45', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which one is a SPORT?"),
      answer: ['soccer'], distractors: ['socks', 'soap', 'sofa']),
  Item(id: 'ei423', skillId: 'es45', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which one is a WEATHER word?"),
      answer: ['rainy'], distractors: ['radio', 'rabbit', 'rainbow']),
  Item(id: 'ei424', skillId: 'es46', exerciseType: ExerciseType.build_sentence,
      prompt: ItemPrompt(text: 'Rearrange the words to make a sentence'),
      answer: ['The', 'cat', 'is', 'sleeping'], distractors: ['on', 'under', 'big']),
  Item(id: 'ei425', skillId: 'es46', exerciseType: ExerciseType.build_sentence,
      prompt: ItemPrompt(text: 'Rearrange the words to make a sentence'),
      answer: ['I', 'like', 'to', 'eat'], distractors: ['sleep', 'run', 'play']),
  Item(id: 'ei426', skillId: 'es46', exerciseType: ExerciseType.build_sentence,
      prompt: ItemPrompt(text: 'Rearrange the words to make a sentence'),
      answer: ['She', 'is', 'reading', 'a'], distractors: ['running', 'jumping', 'swimming']),
  Item(id: 'ei427', skillId: 'es46', exerciseType: ExerciseType.build_sentence,
      prompt: ItemPrompt(text: 'Rearrange the words to make a sentence'),
      answer: ['The', 'dog', 'runs', 'in', 'the'], distractors: ['sleeps', 'eats', 'drinks']),
  Item(id: 'ei428', skillId: 'es46', exerciseType: ExerciseType.build_sentence,
      prompt: ItemPrompt(text: 'Rearrange the words to make a sentence'),
      answer: ['We', 'go', 'to', 'school', 'by'], distractors: ['car', 'sleep', 'eat']),
  Item(id: 'ei429', skillId: 'es46', exerciseType: ExerciseType.build_sentence,
      prompt: ItemPrompt(text: 'Rearrange the words to make a sentence'),
      answer: ['He', 'is', 'playing', 'with', 'a'], distractors: ['sleeping', 'eating', 'reading']),
  Item(id: 'ei430', skillId: 'es46', exerciseType: ExerciseType.build_sentence,
      prompt: ItemPrompt(text: 'Rearrange the words to make a sentence'),
      answer: ['The', 'bird', 'can', 'fly', 'very'], distractors: ['swim', 'run', 'jump']),
  Item(id: 'ei431', skillId: 'es46', exerciseType: ExerciseType.build_sentence,
      prompt: ItemPrompt(text: 'Rearrange the words to make a sentence'),
      answer: ['My', 'mom', 'cooks', 'in', 'the'], distractors: ['bedroom', 'garden', 'bathroom']),
  Item(id: 'ei432', skillId: 'es46', exerciseType: ExerciseType.build_sentence,
      prompt: ItemPrompt(text: 'Rearrange the words to make a sentence'),
      answer: ['The', 'sun', 'is', 'very', 'bright', 'today'], distractors: ['cold', 'dark', 'wet']),
  Item(id: 'ei433', skillId: 'es46', exerciseType: ExerciseType.build_sentence,
      prompt: ItemPrompt(text: 'Rearrange the words to make a sentence'),
      answer: ['I', 'brush', 'my', 'teeth', 'every'], distractors: ['never', 'sometimes', 'always']),
  Item(id: 'ei434', skillId: 'es47', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which sentence is correct?"),
      answer: ['The cat is on the mat.'], distractors: ['The cat on is the mat.', 'On the mat is cat the.', 'Is the cat on mat the.']),
  Item(id: 'ei435', skillId: 'es47', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which sentence is correct?"),
      answer: ['I like to eat apples.'], distractors: ['I to like eat apples.', 'Eat I like to apples.', 'Like I to eat apples.']),
  Item(id: 'ei436', skillId: 'es47', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which sentence is correct?"),
      answer: ['She is my best friend.'], distractors: ['She my is best friend.', 'My best friend is she.', 'Is she my best friend.']),
  Item(id: 'ei437', skillId: 'es47', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which sentence is correct?"),
      answer: ['We play in the park.'], distractors: ['We in play the park.', 'Play we in the park.', 'In the park we play.']),
  Item(id: 'ei438', skillId: 'es47', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which sentence is correct?"),
      answer: ['He reads a book every night.'], distractors: ['He a reads book every night.', 'Reads he a book every night.', 'Every night he reads a book.']),
  Item(id: 'ei439', skillId: 'es47', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which sentence is correct?"),
      answer: ['The bird can fly high.'], distractors: ['The bird fly can high.', 'Can the bird fly high.', 'Fly the bird can high.']),
  Item(id: 'ei440', skillId: 'es47', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which sentence is correct?"),
      answer: ['My sister has a red dress.'], distractors: ['My sister a has red dress.', 'Has my sister a red dress.', 'A red dress my sister has.']),
  Item(id: 'ei441', skillId: 'es47', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Which sentence is correct?"),
      answer: ['They are going to school.'], distractors: ['They going are to school.', 'Are they going to school.', 'To school they are going.']),
  Item(id: 'ei442', skillId: 'es48', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "The baby is ___ because she is hungry."),
      answer: ['crying'], distractors: ['laughing', 'sleeping', 'playing']),
  Item(id: 'ei443', skillId: 'es48', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "The sun makes the room ___ and warm."),
      answer: ['bright'], distractors: ['dark', 'cold', 'wet']),
  Item(id: 'ei444', skillId: 'es48', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "The dog is ___ because it sees a cat."),
      answer: ['barking'], distractors: ['sleeping', 'eating', 'swimming']),
  Item(id: 'ei445', skillId: 'es48', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "I feel ___ when I help my friends."),
      answer: ['happy'], distractors: ['sad', 'angry', 'tired']),
  Item(id: 'ei446', skillId: 'es48', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "The ice cream is very ___ on a hot day."),
      answer: ['cold'], distractors: ['hot', 'warm', 'dry']),
  Item(id: 'ei447', skillId: 'es48', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "The monkey climbed up the ___."),
      answer: ['tree'], distractors: ['water', 'sky', 'road']),
  Item(id: 'ei448', skillId: 'es48', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "She put on her ___ before going outside."),
      answer: ['jacket'], distractors: ['pillow', 'blanket', 'towel']),
  Item(id: 'ei449', skillId: 'es48', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "The flowers ___ very nice in spring."),
      answer: ['bloom'], distractors: ['sleep', 'freeze', 'melt']),
  Item(id: 'ei450', skillId: 'es48', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "He felt ___ after running for a long time."),
      answer: ['tired'], distractors: ['happy', 'angry', 'hungry']),
  Item(id: 'ei451', skillId: 'es48', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "The stars come out at ___."),
      answer: ['night'], distractors: ['morning', 'noon', 'afternoon']),
  Item(id: 'ei452', skillId: 'es49', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Match the animal to its sound: Dog"),
      answer: ['woof'], distractors: ['meow', 'moo', 'oink']),
  Item(id: 'ei453', skillId: 'es49', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Match the animal to its sound: Cat"),
      answer: ['meow'], distractors: ['woof', 'quack', 'baa']),
  Item(id: 'ei454', skillId: 'es49', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Match the animal to its sound: Cow"),
      answer: ['moo'], distractors: ['woof', 'meow', 'cluck']),
  Item(id: 'ei455', skillId: 'es49', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Match the animal to its home: Bird"),
      answer: ['nest'], distractors: ['den', 'stable', 'cave']),
  Item(id: 'ei456', skillId: 'es49', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Match the animal to its home: Fish"),
      answer: ['water'], distractors: ['tree', 'ground', 'cave']),
  Item(id: 'ei457', skillId: 'es49', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Match the food to its color: Carrot"),
      answer: ['orange'], distractors: ['green', 'red', 'yellow']),
  Item(id: 'ei458', skillId: 'es49', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Match the food to its color: Banana"),
      answer: ['yellow'], distractors: ['red', 'green', 'purple']),
  Item(id: 'ei459', skillId: 'es49', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Match the season: Snow falls in"),
      answer: ['winter'], distractors: ['summer', 'spring', 'autumn']),
  Item(id: 'ei460', skillId: 'es49', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Match the season: Flowers bloom in"),
      answer: ['spring'], distractors: ['winter', 'summer', 'autumn']),
  Item(id: 'ei461', skillId: 'es49', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: "Match the season: Leaves fall in"),
      answer: ['autumn'], distractors: ['spring', 'summer', 'winter']),
];
