import 'subject.dart';
import 'exercise_type.dart';
import 'unit.dart';
import 'skill.dart';
import 'item.dart';

// ─── Homework Units ───────────────────────────────────────────────────────────
// Homework is a separate section from the regular curriculum path.
// Homework skills have no prerequisites and are always unlocked.
final List<Unit> homeworkUnits = [
  Unit(id: 'eng-hw', subject: Subject.ENGLISH, code: 'ENG-HW', title: 'Homework', skillIds: ['hw1', 'hw2', 'hw3', 'hw4', 'hw5', 'hw6', 'hw7']),
];

// ─── Homework Skills ──────────────────────────────────────────────────────────
final List<Skill> homeworkSkills = [
  Skill(id: 'hw1', subject: Subject.ENGLISH, unitCode: 'ENG-HW',
      title: 'Spelling Practice', icon: '📝', prerequisites: [],
      itemIds: ['ei462','ei463','ei464','ei465','ei466','ei467','ei468','ei469','ei470','ei471']),
  Skill(id: 'hw2', subject: Subject.ENGLISH, unitCode: 'ENG-HW',
      title: 'Spelling Practice 2', icon: '✏️', prerequisites: [],
      itemIds: ['ei472','ei473','ei474','ei475','ei476','ei477','ei478','ei479','ei480','ei481']),  Skill(id: 'hw3', subject: Subject.ENGLISH, unitCode: 'ENG-HW',
      title: 'Spelling Practice 3', icon: '🚀', prerequisites: [],
      itemIds: ['ei482','ei483','ei484','ei485','ei486','ei487','ei488','ei489','ei490','ei491']),
  Skill(id: 'hw4', subject: Subject.ENGLISH, unitCode: 'ENG-HW',
      title: 'Spelling Practice 4', icon: '🔤', prerequisites: [],
      itemIds: ['ei492','ei493','ei494','ei495','ei496','ei497','ei498','ei499','ei500','ei501']),
  Skill(id: 'hw5', subject: Subject.ENGLISH, unitCode: 'ENG-HW',
      title: 'Spelling Practice 5', icon: '🏙️', prerequisites: [],
      itemIds: ['ei502','ei503','ei504','ei505','ei506','ei507','ei508','ei509','ei510','ei511']),  Skill(id: 'hw6', subject: Subject.ENGLISH, unitCode: 'ENG-HW',
      title: 'Spelling Practice 6', icon: '📐', prerequisites: [],
      itemIds: ['ei512','ei513','ei514','ei515','ei516','ei517','ei518','ei519','ei520','ei521']),  Skill(id: 'hw7', subject: Subject.ENGLISH, unitCode: 'ENG-HW',
      title: 'Spelling Practice 7', icon: '➕', prerequisites: [],
      itemIds: ['ei522','ei523','ei524','ei525','ei526','ei527','ei528','ei529','ei530','ei531']),
];

// ─── Homework Items ───────────────────────────────────────────────────────────
final List<Item> homeworkItems = [
  Item(id: 'ei462', skillId: 'hw1', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🏢 (up to date, not old-fashioned)'),
      answer: ['m', 'o', 'd', 'e', 'r', 'n'], distractors: ['a', 'p', 's']),
  Item(id: 'ei463', skillId: 'hw1', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🎨 (a plan or drawing for something)'),
      answer: ['d', 'e', 's', 'i', 'g', 'n'], distractors: ['a', 'o', 'r']),
  Item(id: 'ei464', skillId: 'hw1', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: ⭕ (a round shape with no corners)'),
      answer: ['c', 'i', 'r', 'c', 'l', 'e'], distractors: ['a', 'o', 's']),
  Item(id: 'ei465', skillId: 'hw1', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 📐 (the edges where sides of something meet)'),
      answer: ['c', 'o', 'r', 'n', 'e', 'r', 's'], distractors: ['a', 'd', 't']),
  Item(id: 'ei466', skillId: 'hw1', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🛠️ (to make or produce something)'),
      answer: ['c', 'r', 'e', 'a', 't', 'e'], distractors: ['o', 's', 'i']),
  Item(id: 'ei467', skillId: 'hw1', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🔄 (to make something different)'),
      answer: ['c', 'h', 'a', 'n', 'g', 'e'], distractors: ['o', 'r', 's']),
  Item(id: 'ei468', skillId: 'hw1', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🎁 (to give or show something)'),
      answer: ['p', 'r', 'e', 's', 'e', 'n', 't'], distractors: ['a', 'd', 'o']),
  Item(id: 'ei469', skillId: 'hw1', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🟦 (a shape with 4 equal sides)'),
      answer: ['s', 'q', 'u', 'a', 'r', 'e'], distractors: ['c', 'o', 'i']),
  Item(id: 'ei470', skillId: 'hw1', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🧈 (having an even surface, not rough)'),
      answer: ['s', 'm', 'o', 'o', 't', 'h'], distractors: ['a', 'e', 'n']),
  Item(id: 'ei471', skillId: 'hw1', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🏗️ (to construct something)'),
      answer: ['b', 'u', 'i', 'l', 'd'], distractors: ['a', 'e', 'o']),
  Item(id: 'ei472', skillId: 'hw2', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🦎 (to change so you fit a new place or situation)'),
      answer: ['a', 'd', 'a', 'p', 't'], distractors: ['e', 'o', 'b']),
  Item(id: 'ei473', skillId: 'hw2', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🎨 (a plan or drawing for something)'),
      answer: ['d', 'e', 's', 'i', 'g', 'n'], distractors: ['a', 'y', 'r']),
  Item(id: 'ei474', skillId: 'hw2', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: ⛅ (sun, rain or wind — what the sky is doing today)'),
      answer: ['w', 'e', 'a', 't', 'h', 'e', 'r'], distractors: ['i', 'o', 'n']),
  Item(id: 'ei475', skillId: 'hw2', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🌍 (the usual weather of a place over many years)'),
      answer: ['c', 'l', 'i', 'm', 'a', 't', 'e'], distractors: ['o', 'y', 'n']),
  Item(id: 'ei476', skillId: 'hw2', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🛡️ (to keep something safe from harm)'),
      answer: ['p', 'r', 'o', 't', 'e', 'c', 't'], distractors: ['a', 'i', 'k']),
  Item(id: 'ei477', skillId: 'hw2', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 👥 (more than one person)'),
      answer: ['p', 'e', 'o', 'p', 'l', 'e'], distractors: ['a', 'i', 'u']),
  Item(id: 'ei478', skillId: 'hw2', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🔄 (to make something different)'),
      answer: ['c', 'h', 'a', 'n', 'g', 'e'], distractors: ['o', 'r', 's']),
  Item(id: 'ei479', skillId: 'hw2', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: ❓ (for the reason that)'),
      answer: ['b', 'e', 'c', 'a', 'u', 's', 'e'], distractors: ['o', 'i', 'z']),
  Item(id: 'ei480', skillId: 'hw2', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🗣️ (to say what something is like)'),
      answer: ['d', 'e', 's', 'c', 'r', 'i', 'b', 'e'], distractors: ['a', 'o', 't']),
  Item(id: 'ei481', skillId: 'hw2', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: ⭐ (the one you like best of all)'),
      answer: ['f', 'a', 'v', 'o', 'u', 'r', 'i', 't', 'e'], distractors: ['y', 's', 'l']),
  Item(id: 'ei482', skillId: 'hw3', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🚀 (the huge dark area where the stars and planets are)'),
      answer: ['s', 'p', 'a', 'c', 'e'], distractors: ['i', 'o', 'y']),
  Item(id: 'ei483', skillId: 'hw3', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: ☀️ (full of light, shining strongly)'),
      answer: ['b', 'r', 'i', 'g', 'h', 't'], distractors: ['e', 'a', 'o']),
  Item(id: 'ei484', skillId: 'hw3', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🌍 (the planet we all live on)'),
      answer: ['w', 'o', 'r', 'l', 'd'], distractors: ['a', 'e', 'i']),
  Item(id: 'ei485', skillId: 'hw3', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🐱🐱 (more than one — like cats, not cat)'),
      answer: ['p', 'l', 'u', 'r', 'a', 'l'], distractors: ['e', 'o', 'y']),
  Item(id: 'ei486', skillId: 'hw3', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 😊 (feeling glad and full of joy)'),
      answer: ['h', 'a', 'p', 'p', 'y'], distractors: ['e', 'i', 'o']),
  Item(id: 'ei487', skillId: 'hw3', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🔄 (on every side, in a circle)'),
      answer: ['a', 'r', 'o', 'u', 'n', 'd'], distractors: ['e', 'i', 'w']),
  Item(id: 'ei488', skillId: 'hw3', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🪨 (not smooth, bumpy to touch)'),
      answer: ['r', 'o', 'u', 'g', 'h'], distractors: ['a', 'e', 'f']),
  Item(id: 'ei489', skillId: 'hw3', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🔷 (the form of something — circle, square, star)'),
      answer: ['s', 'h', 'a', 'p', 'e'], distractors: ['i', 'o', 'u']),
  Item(id: 'ei490', skillId: 'hw3', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🔊 (a sound that is loud or not nice to hear)'),
      answer: ['n', 'o', 'i', 's', 'e'], distractors: ['a', 'u', 'y']),
  Item(id: 'ei491', skillId: 'hw3', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 👨‍👩‍👧 (the people you live with and love)'),
      answer: ['f', 'a', 'm', 'i', 'l', 'y'], distractors: ['e', 'o', 'u']),
  Item(id: 'ei492', skillId: 'hw4', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: ❓ (not there, lost or left out)'),
      answer: ['m', 'i', 's', 's', 'i', 'n', 'g'], distractors: ['a', 'e', 'o']),
  Item(id: 'ei493', skillId: 'hw4', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 1️⃣ (just one — like cat, not cats)'),
      answer: ['s', 'i', 'n', 'g', 'u', 'l', 'a', 'r'], distractors: ['e', 'o', 'y']),
  Item(id: 'ei494', skillId: 'hw4', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🤫 (making no sound at all)'),
      answer: ['s', 'i', 'l', 'e', 'n', 't'], distractors: ['a', 'o', 'u']),
  Item(id: 'ei495', skillId: 'hw4', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🎵 (something you can hear)'),
      answer: ['s', 'o', 'u', 'n', 'd'], distractors: ['a', 'e', 'i']),
  Item(id: 'ei496', skillId: 'hw4', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🎨 (a plan or drawing for something)'),
      answer: ['d', 'e', 's', 'i', 'g', 'n'], distractors: ['a', 'y', 'r']),
  Item(id: 'ei497', skillId: 'hw4', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🐱🐱 (more than one — like cats, not cat)'),
      answer: ['p', 'l', 'u', 'r', 'a', 'l'], distractors: ['e', 'o', 'y']),
  Item(id: 'ei498', skillId: 'hw4', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🏠 (a building where people live)'),
      answer: ['h', 'o', 'u', 's', 'e'], distractors: ['a', 'i', 'w']),
  Item(id: 'ei499', skillId: 'hw4', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🅰️ (a, e, i, o or u)'),
      answer: ['v', 'o', 'w', 'e', 'l'], distractors: ['a', 'i', 'u']),
  Item(id: 'ei500', skillId: 'hw4', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🧩 (something that repeats again and again)'),
      answer: ['p', 'a', 't', 't', 'e', 'r', 'n'], distractors: ['i', 'o', 'u']),
  Item(id: 'ei501', skillId: 'hw4', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 👨‍👩‍👧 (the people you live with and love)'),
      answer: ['f', 'a', 'm', 'i', 'l', 'y'], distractors: ['e', 'o', 'u']),
  Item(id: 'ei502', skillId: 'hw5', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🌳 (a green place with grass and trees to play in)'),
      answer: ['p', 'a', 'r', 'k'], distractors: ['e', 'c', 'i']),
  Item(id: 'ei503', skillId: 'hw5', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 📦 (any object — not a person or animal)'),
      answer: ['t', 'h', 'i', 'n', 'g'], distractors: ['a', 'e', 'k']),
  Item(id: 'ei504', skillId: 'hw5', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 📍 (where something is)'),
      answer: ['p', 'l', 'a', 'c', 'e'], distractors: ['i', 'o', 's']),
  Item(id: 'ei505', skillId: 'hw5', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🧑 (one human — a man, woman or child)'),
      answer: ['p', 'e', 'r', 's', 'o', 'n'], distractors: ['a', 'i', 'u']),
  Item(id: 'ei506', skillId: 'hw5', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🐘 (a living creature like a dog, cat or elephant)'),
      answer: ['a', 'n', 'i', 'm', 'a', 'l'], distractors: ['e', 'o', 'u']),
  Item(id: 'ei507', skillId: 'hw5', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🏢 (a place where people go to work)'),
      answer: ['o', 'f', 'f', 'i', 'c', 'e'], distractors: ['a', 's', 'u']),
  Item(id: 'ei508', skillId: 'hw5', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🏫 (the place you go to learn)'),
      answer: ['s', 'c', 'h', 'o', 'o', 'l'], distractors: ['a', 'e', 'u']),
  Item(id: 'ei509', skillId: 'hw5', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🌟 (known by lots and lots of people)'),
      answer: ['f', 'a', 'm', 'o', 'u', 's'], distractors: ['e', 'i', 'y']),
  Item(id: 'ei510', skillId: 'hw5', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🏥 (where doctors help people who are sick)'),
      answer: ['h', 'o', 's', 'p', 'i', 't', 'a', 'l'], distractors: ['e', 'u', 'y']),
  Item(id: 'ei511', skillId: 'hw5', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🗺️ (a land with its own people and flag, like India)'),
      answer: ['c', 'o', 'u', 'n', 't', 'r', 'y'], distractors: ['a', 'e', 'i']),
  Item(id: 'ei512', skillId: 'hw6', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🚀 (the huge dark area where the stars and planets are)'),
      answer: ['s', 'p', 'a', 'c', 'e'], distractors: ['i', 'o', 'y']),
  Item(id: 'ei513', skillId: 'hw6', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🔺 (a clear glass shape that splits light into a rainbow)'),
      answer: ['p', 'r', 'i', 's', 'm'], distractors: ['a', 'e', 'o']),
  Item(id: 'ei514', skillId: 'hw6', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: ⭕ (a round shape with no corners)'),
      answer: ['c', 'i', 'r', 'c', 'l', 'e'], distractors: ['a', 'o', 's']),
  Item(id: 'ei515', skillId: 'hw6', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🛠️ (to make or produce something)'),
      answer: ['c', 'r', 'e', 'a', 't', 'e'], distractors: ['o', 's', 'i']),
  Item(id: 'ei516', skillId: 'hw6', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: ⚽ (a perfectly round solid shape, like a ball)'),
      answer: ['s', 'p', 'h', 'e', 'r', 'e'], distractors: ['a', 'o', 't']),
  Item(id: 'ei517', skillId: 'hw6', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🟦 (a shape with 4 equal sides)'),
      answer: ['s', 'q', 'u', 'a', 'r', 'e'], distractors: ['c', 'o', 'i']),
  Item(id: 'ei518', skillId: 'hw6', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🧈 (having an even surface, not rough)'),
      answer: ['s', 'm', 'o', 'o', 't', 'h'], distractors: ['a', 'e', 'n']),
  Item(id: 'ei519', skillId: 'hw6', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🏢 (up to date, not old-fashioned)'),
      answer: ['m', 'o', 'd', 'e', 'r', 'n'], distractors: ['a', 'p', 's']),
  Item(id: 'ei520', skillId: 'hw6', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 📐 (the points where two sides meet)'),
      answer: ['c', 'o', 'r', 'n', 'e', 'r', 's'], distractors: ['a', 'd', 't']),
  Item(id: 'ei521', skillId: 'hw6', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🟥 (a shape with 4 sides — two long, two short)'),
      answer: ['r', 'e', 'c', 't', 'a', 'n', 'g', 'l', 'e'], distractors: ['i', 'o', 's']),
  Item(id: 'ei522', skillId: 'hw7', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: ➕ (to put numbers or things together to get a bigger total)'),
      answer: ['a', 'd', 'd'], distractors: ['e', 'o', 'p']),
  Item(id: 'ei523', skillId: 'hw7', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: ➕ (the sign + that means "and" or "added to")'),
      answer: ['p', 'l', 'u', 's'], distractors: ['a', 'o', 'd']),
  Item(id: 'ei524', skillId: 'hw7', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🟰 (the same amount as, like 2 + 2 = 4)'),
      answer: ['e', 'q', 'u', 'a', 'l'], distractors: ['i', 'o', 's']),
  Item(id: 'ei525', skillId: 'hw7', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🔮 (to say what you think will happen next)'),
      answer: ['p', 'r', 'e', 'd', 'i', 'c', 't'], distractors: ['a', 'l', 'n']),
  Item(id: 'ei526', skillId: 'hw7', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🌍 (the usual weather of a place over many years)'),
      answer: ['c', 'l', 'i', 'm', 'a', 't', 'e'], distractors: ['o', 'y', 'n']),
  Item(id: 'ei527', skillId: 'hw7', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🧩 (something hard that needs to be solved)'),
      answer: ['p', 'r', 'o', 'b', 'l', 'e', 'm'], distractors: ['a', 'i', 't']),
  Item(id: 'ei528', skillId: 'hw7', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🧈 (having an even surface, not rough)'),
      answer: ['s', 'm', 'o', 'o', 't', 'h'], distractors: ['a', 'e', 'n']),
  Item(id: 'ei529', skillId: 'hw7', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🗣️ (to say what something is like)'),
      answer: ['d', 'e', 's', 'c', 'r', 'i', 'b', 'e'], distractors: ['a', 'o', 't']),
  Item(id: 'ei530', skillId: 'hw7', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: 🏢 (up to date, not old-fashioned)'),
      answer: ['m', 'o', 'd', 'e', 'r', 'n'], distractors: ['a', 'p', 's']),
  Item(id: 'ei531', skillId: 'hw7', exerciseType: ExerciseType.spell_tiles,
      prompt: ItemPrompt(text: 'Spell this: ⭐ (the one you like best of all)'),
      answer: ['f', 'a', 'v', 'o', 'u', 'r', 'i', 't', 'e'], distractors: ['y', 's', 'l']),
];
