import 'subject.dart';
import 'exercise_type.dart';
import 'unit.dart';
import 'skill.dart';
import 'item.dart';

// ─────────────────────────────────────────────────────────────────────────────
// UNITS
// ─────────────────────────────────────────────────────────────────────────────

final List<Unit> mathCambridgeUnits = [
  Unit(id: 'M1', subject: Subject.MATH, code: 'MATH-M1', title: 'Counting & Numbers (LKG)',
      skillIds: ['ms1', 'ms2', 'ms3', 'ms4']),
  Unit(id: 'M2', subject: Subject.MATH, code: 'MATH-M2', title: 'Numbers to 100',
      skillIds: ['ms5', 'ms6', 'ms7', 'ms8']),
  Unit(id: 'M3', subject: Subject.MATH, code: 'MATH-M3', title: 'Numbers to 500',
      skillIds: ['ms9', 'ms10', 'ms11', 'ms12', 'ms13']),
  Unit(id: 'M4', subject: Subject.MATH, code: 'MATH-M4', title: 'Addition',
      skillIds: ['ms14', 'ms15', 'ms16', 'ms17']),
  Unit(id: 'M5', subject: Subject.MATH, code: 'MATH-M5', title: 'Subtraction',
      skillIds: ['ms18', 'ms19', 'ms20', 'ms21']),
  Unit(id: 'M6', subject: Subject.MATH, code: 'MATH-M6', title: 'Shapes & Patterns',
      skillIds: ['ms22', 'ms23', 'ms24']),
  Unit(id: 'M7', subject: Subject.MATH, code: 'MATH-M7', title: 'Measurement',
      skillIds: ['ms25', 'ms26', 'ms27']),
  Unit(id: 'M8', subject: Subject.MATH, code: 'MATH-M8', title: 'Time & Money',
      skillIds: ['ms28', 'ms29', 'ms30']),
  Unit(id: 'M9', subject: Subject.MATH, code: 'MATH-M9', title: 'Number Sense & Ordering',
      skillIds: ['ms31', 'ms32', 'ms33', 'ms34', 'ms35']),
  Unit(id: 'M10', subject: Subject.MATH, code: 'MATH-M10', title: 'Addition & Subtraction Mastery',
      skillIds: ['ms36', 'ms37', 'ms38', 'ms39', 'ms40']),
  Unit(id: 'M11', subject: Subject.MATH, code: 'MATH-M11', title: 'Counting & Number Bonds',
      skillIds: ['ms41', 'ms42', 'ms43']),
];

// ─────────────────────────────────────────────────────────────────────────────
// SKILLS
// ─────────────────────────────────────────────────────────────────────────────

final List<Skill> mathCambridgeSkills = [
  // M1 – Counting & Numbers
  Skill(id: 'ms1', subject: Subject.MATH, unitCode: 'MATH-M1', title: 'Count to 10',
      icon: '🔢', prerequisites: [],
      itemIds: ['mi100','mi101','mi102','mi103','mi104','mi105','mi106','mi107']),
  Skill(id: 'ms2', subject: Subject.MATH, unitCode: 'MATH-M1', title: 'Count to 20',
      icon: '🔢', prerequisites: ['ms1'],
      itemIds: ['mi108','mi109','mi110','mi111','mi112','mi113','mi114','mi115']),
  Skill(id: 'ms3', subject: Subject.MATH, unitCode: 'MATH-M1', title: 'Number Recognition 1-20',
      icon: '👀', prerequisites: ['ms1'],
      itemIds: ['mi116','mi117','mi118','mi119','mi120','mi121','mi122','mi123']),
  Skill(id: 'ms4', subject: Subject.MATH, unitCode: 'MATH-M1', title: 'Before, After, Between',
      icon: '↔️', prerequisites: ['ms2'],
      itemIds: ['mi124','mi125','mi126','mi127','mi128','mi129','mi130','mi131']),
  // M2 – Numbers to 100
  Skill(id: 'ms5', subject: Subject.MATH, unitCode: 'MATH-M2', title: 'Count to 50',
      icon: '🔢', prerequisites: ['ms4'],
      itemIds: ['mi132','mi133','mi134','mi135','mi136','mi137','mi138','mi139']),
  Skill(id: 'ms6', subject: Subject.MATH, unitCode: 'MATH-M2', title: 'Count to 100',
      icon: '🔢', prerequisites: ['ms5'],
      itemIds: ['mi140','mi141','mi142','mi143','mi144','mi145','mi146','mi147']),
  Skill(id: 'ms7', subject: Subject.MATH, unitCode: 'MATH-M2', title: 'Place Value - Ones and Tens',
      icon: '🏗️', prerequisites: ['ms5'],
      itemIds: ['mi148','mi149','mi150','mi151','mi152','mi153','mi154','mi155']),
  Skill(id: 'ms8', subject: Subject.MATH, unitCode: 'MATH-M2', title: 'Skip Counting by 2, 5, 10',
      icon: '⏭️', prerequisites: ['ms6'],
      itemIds: ['mi156','mi157','mi158','mi159','mi160','mi161','mi162','mi163','mi164','mi165']),
  // M3 – Numbers to 500
  Skill(id: 'ms9', subject: Subject.MATH, unitCode: 'MATH-M3', title: 'Count to 200',
      icon: '🔢', prerequisites: ['ms6'],
      itemIds: ['mi166','mi167','mi168','mi169','mi170','mi171','mi172','mi173']),
  Skill(id: 'ms10', subject: Subject.MATH, unitCode: 'MATH-M3', title: 'Count to 500',
      icon: '🔢', prerequisites: ['ms9'],
      itemIds: ['mi174','mi175','mi176','mi177','mi178','mi179','mi180','mi181']),
  Skill(id: 'ms11', subject: Subject.MATH, unitCode: 'MATH-M3', title: 'Hundreds, Tens, Ones',
      icon: '🏗️', prerequisites: ['ms7'],
      itemIds: ['mi182','mi183','mi184','mi185','mi186','mi187','mi188','mi189']),
  Skill(id: 'ms12', subject: Subject.MATH, unitCode: 'MATH-M3', title: 'Reading 3-Digit Numbers',
      icon: '📖', prerequisites: ['ms11'],
      itemIds: ['mi190','mi191','mi192','mi193','mi194','mi195','mi196','mi197']),
  Skill(id: 'ms13', subject: Subject.MATH, unitCode: 'MATH-M3', title: 'Comparing Numbers',
      icon: '⚖️', prerequisites: ['ms10'],
      itemIds: ['mi198','mi199','mi200','mi201','mi202','mi203','mi204','mi205','mi206','mi207']),
  // M4 – Addition
  Skill(id: 'ms14', subject: Subject.MATH, unitCode: 'MATH-M4', title: 'Add within 10',
      icon: '➕', prerequisites: ['ms2'],
      itemIds: ['mi208','mi209','mi210','mi211','mi212','mi213','mi214','mi215']),
  Skill(id: 'ms15', subject: Subject.MATH, unitCode: 'MATH-M4', title: 'Add within 20',
      icon: '➕', prerequisites: ['ms14'],
      itemIds: ['mi216','mi217','mi218','mi219','mi220','mi221','mi222','mi223']),
  Skill(id: 'ms16', subject: Subject.MATH, unitCode: 'MATH-M4', title: 'Add 2-Digit (No Carry)',
      icon: '➕', prerequisites: ['ms6'],
      itemIds: ['mi224','mi225','mi226','mi227','mi228','mi229','mi230','mi231']),
  Skill(id: 'ms17', subject: Subject.MATH, unitCode: 'MATH-M4', title: 'Add 2-Digit (With Carry)',
      icon: '➕', prerequisites: ['ms16'],
      itemIds: ['mi232','mi233','mi234','mi235','mi236','mi237','mi238','mi239']),
  // M5 – Subtraction
  Skill(id: 'ms18', subject: Subject.MATH, unitCode: 'MATH-M5', title: 'Subtract within 10',
      icon: '➖', prerequisites: ['ms14'],
      itemIds: ['mi240','mi241','mi242','mi243','mi244','mi245','mi246','mi247']),
  Skill(id: 'ms19', subject: Subject.MATH, unitCode: 'MATH-M5', title: 'Subtract within 20',
      icon: '➖', prerequisites: ['ms18'],
      itemIds: ['mi248','mi249','mi250','mi251','mi252','mi253','mi254','mi255']),
  Skill(id: 'ms20', subject: Subject.MATH, unitCode: 'MATH-M5', title: 'Subtract 2-Digit (No Borrow)',
      icon: '➖', prerequisites: ['ms16'],
      itemIds: ['mi256','mi257','mi258','mi259','mi260','mi261','mi262','mi263']),
  Skill(id: 'ms21', subject: Subject.MATH, unitCode: 'MATH-M5', title: 'Subtract 2-Digit (With Borrow)',
      icon: '➖', prerequisites: ['ms20'],
      itemIds: ['mi264','mi265','mi266','mi267','mi268','mi269','mi270','mi271']),
  // M6 – Shapes & Patterns
  Skill(id: 'ms22', subject: Subject.MATH, unitCode: 'MATH-M6', title: '2D Shapes',
      icon: '🔷', prerequisites: [],
      itemIds: ['mi272','mi273','mi274','mi275','mi276','mi277','mi278','mi279']),
  Skill(id: 'ms23', subject: Subject.MATH, unitCode: 'MATH-M6', title: '3D Shapes',
      icon: '🧊', prerequisites: ['ms22'],
      itemIds: ['mi280','mi281','mi282','mi283','mi284','mi285','mi286','mi287']),
  Skill(id: 'ms24', subject: Subject.MATH, unitCode: 'MATH-M6', title: 'Patterns',
      icon: '🔁', prerequisites: ['ms22'],
      itemIds: ['mi288','mi289','mi290','mi291','mi292','mi293','mi294','mi295']),
  // M7 – Measurement
  Skill(id: 'ms25', subject: Subject.MATH, unitCode: 'MATH-M7', title: 'Big and Small',
      icon: '📏', prerequisites: [],
      itemIds: ['mi296','mi297','mi298','mi299','mi300','mi301','mi302','mi303']),
  Skill(id: 'ms26', subject: Subject.MATH, unitCode: 'MATH-M7', title: 'Tall and Short',
      icon: '📐', prerequisites: ['ms25'],
      itemIds: ['mi304','mi305','mi306','mi307','mi308','mi309','mi310','mi311']),
  Skill(id: 'ms27', subject: Subject.MATH, unitCode: 'MATH-M7', title: 'Heavy and Light',
      icon: '⚖️', prerequisites: ['ms25'],
      itemIds: ['mi312','mi313','mi314','mi315','mi316','mi317','mi318','mi319']),
  // M8 – Time & Money
  Skill(id: 'ms28', subject: Subject.MATH, unitCode: 'MATH-M8', title: 'Days of the Week',
      icon: '📅', prerequisites: [],
      itemIds: ['mi320','mi321','mi322','mi323','mi324','mi325','mi326','mi327']),
  Skill(id: 'ms29', subject: Subject.MATH, unitCode: 'MATH-M8', title: 'Reading Clock (Hours)',
      icon: '🕐', prerequisites: ['ms28'],
      itemIds: ['mi328','mi329','mi330','mi331','mi332','mi333','mi334','mi335']),
  Skill(id: 'ms30', subject: Subject.MATH, unitCode: 'MATH-M8', title: 'Coins & Money',
      icon: '🪙', prerequisites: ['ms2'],
      itemIds: ['mi336','mi337','mi338','mi339','mi340','mi341','mi342','mi343']),
  // M9 – Number Sense & Ordering
  Skill(id: 'ms31', subject: Subject.MATH, unitCode: 'MATH-M9', title: 'Number Bonds to 10',
      icon: '🔗', prerequisites: [],
      itemIds: ['mi344','mi345','mi346','mi347','mi348','mi349','mi350','mi351','mi352','mi353']),
  Skill(id: 'ms32', subject: Subject.MATH, unitCode: 'MATH-M9', title: 'Number Bonds to 20',
      icon: '🔗', prerequisites: ['ms31'],
      itemIds: ['mi354','mi355','mi356','mi357','mi358','mi359','mi360','mi361','mi362','mi363']),
  Skill(id: 'ms33', subject: Subject.MATH, unitCode: 'MATH-M9', title: 'Ascending & Descending Order',
      icon: '⬆️', prerequisites: ['ms31'],
      itemIds: ['mi364','mi365','mi366','mi367','mi368','mi369','mi370','mi371','mi372','mi373']),
  Skill(id: 'ms34', subject: Subject.MATH, unitCode: 'MATH-M9', title: 'Missing Numbers',
      icon: '❓', prerequisites: ['ms31'],
      itemIds: ['mi374','mi375','mi376','mi377','mi378','mi379','mi380','mi381','mi382','mi383']),
  Skill(id: 'ms35', subject: Subject.MATH, unitCode: 'MATH-M9', title: 'Adding by Counting On',
      icon: '👆', prerequisites: ['ms31'],
      itemIds: ['mi384','mi385','mi386','mi387','mi388','mi389','mi390','mi391','mi392','mi393']),
  // M10 – Addition & Subtraction Mastery
  Skill(id: 'ms36', subject: Subject.MATH, unitCode: 'MATH-M10', title: 'Addition Facts: Sums to 10',
      icon: '➕', prerequisites: [],
      itemIds: ['mi394','mi395','mi396','mi397','mi398','mi399','mi400','mi401','mi402','mi403','mi404','mi405']),
  Skill(id: 'ms37', subject: Subject.MATH, unitCode: 'MATH-M10', title: 'Addition Facts: Sums 11-20',
      icon: '➕', prerequisites: ['ms36'],
      itemIds: ['mi406','mi407','mi408','mi409','mi410','mi411','mi412','mi413','mi414','mi415','mi416','mi417']),
  Skill(id: 'ms38', subject: Subject.MATH, unitCode: 'MATH-M10', title: 'Subtraction Facts: Within 10',
      icon: '➖', prerequisites: ['ms36'],
      itemIds: ['mi418','mi419','mi420','mi421','mi422','mi423','mi424','mi425','mi426','mi427','mi428','mi429']),
  Skill(id: 'ms39', subject: Subject.MATH, unitCode: 'MATH-M10', title: 'Subtraction Facts: Within 20',
      icon: '➖', prerequisites: ['ms38'],
      itemIds: ['mi430','mi431','mi432','mi433','mi434','mi435','mi436','mi437','mi438','mi439','mi440','mi441']),
  Skill(id: 'ms40', subject: Subject.MATH, unitCode: 'MATH-M10', title: 'Mixed Add & Subtract to 20',
      icon: '🔀', prerequisites: ['ms37', 'ms39'],
      itemIds: ['mi442','mi443','mi444','mi445','mi446','mi447','mi448','mi449','mi450','mi451','mi452','mi453']),


  // M11 – Counting & Number Bonds
  Skill(id: 'ms41', subject: Subject.MATH, unitCode: 'MATH-M11', title: 'Count to 100',
      icon: '💯', prerequisites: [],
      itemIds: ['mi454','mi455','mi456','mi457','mi458','mi459','mi460','mi461','mi462','mi463','mi464','mi465']),
  Skill(id: 'ms42', subject: Subject.MATH, unitCode: 'MATH-M11', title: 'Number Bonds (4,5,6,7)',
      icon: '🔗', prerequisites: ['ms41'],
      itemIds: ['mi466','mi467','mi468','mi469','mi470','mi471','mi472','mi473','mi474','mi475','mi476','mi477']),
  Skill(id: 'ms43', subject: Subject.MATH, unitCode: 'MATH-M11', title: 'Descending 20 to 1',
      icon: '⬇️', prerequisites: ['ms41'],
      itemIds: ['mi478','mi479','mi480','mi481','mi482','mi483','mi484','mi485','mi486','mi487']),
];

// ─────────────────────────────────────────────────────────────────────────────
// ITEMS
// ─────────────────────────────────────────────────────────────────────────────

final List<Item> mathCambridgeItems = [
  // ═══════════════════════════════════════════════════════════════════════════
  // ms1 – Count to 10  (Count emoji objects)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi100', skillId: 'ms1', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many? ⭐⭐⭐'),
      answer: ['3'], distractors: ['2', '4', '5']),
  Item(id: 'mi101', skillId: 'ms1', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many? 🍎🍎🍎🍎🍎'),
      answer: ['5'], distractors: ['4', '6', '3']),
  Item(id: 'mi102', skillId: 'ms1', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many? 🎈🎈🎈🎈🎈🎈🎈'),
      answer: ['7'], distractors: ['6', '8', '5']),
  Item(id: 'mi103', skillId: 'ms1', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many? 🐱🐱'),
      answer: ['2'], distractors: ['1', '3', '4']),
  Item(id: 'mi104', skillId: 'ms1', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many? 🌺🌺🌺🌺🌺🌺🌺🌺🌺'),
      answer: ['9'], distractors: ['8', '10', '7']),
  Item(id: 'mi105', skillId: 'ms1', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many? 🦋🦋🦋🦋🦋🦋'),
      answer: ['6'], distractors: ['5', '7', '4']),
  Item(id: 'mi106', skillId: 'ms1', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many? 🍪🍪🍪🍪'),
      answer: ['4'], distractors: ['3', '5', '6']),
  Item(id: 'mi107', skillId: 'ms1', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many? 🐠🐠🐠🐠🐠🐠🐠🐠'),
      answer: ['8'], distractors: ['7', '9', '6']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms2 – Count to 20  (What comes after / before)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi108', skillId: 'ms2', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes after 15?'),
      answer: ['16'], distractors: ['14', '17', '13']),
  Item(id: 'mi109', skillId: 'ms2', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes before 13?'),
      answer: ['12'], distractors: ['14', '11', '10']),
  Item(id: 'mi110', skillId: 'ms2', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes after 19?'),
      answer: ['20'], distractors: ['18', '17', '16']),
  Item(id: 'mi111', skillId: 'ms2', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes after 11?'),
      answer: ['12'], distractors: ['10', '13', '14']),
  Item(id: 'mi112', skillId: 'ms2', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes before 18?'),
      answer: ['17'], distractors: ['19', '16', '15']),
  Item(id: 'mi113', skillId: 'ms2', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes after 14?'),
      answer: ['15'], distractors: ['13', '16', '12']),
  Item(id: 'mi114', skillId: 'ms2', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes before 20?'),
      answer: ['19'], distractors: ['18', '17', '16']),
  Item(id: 'mi115', skillId: 'ms2', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes after 16?'),
      answer: ['17'], distractors: ['15', '18', '14']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms3 – Number Recognition 1-20
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi116', skillId: 'ms3', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Which number shows "five"?'),
      answer: ['5'], distractors: ['4', '6', '15']),
  Item(id: 'mi117', skillId: 'ms3', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Which number shows "twelve"?'),
      answer: ['12'], distractors: ['2', '21', '20']),
  Item(id: 'mi118', skillId: 'ms3', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Which number shows "eight"?'),
      answer: ['8'], distractors: ['18', '80', '6']),
  Item(id: 'mi119', skillId: 'ms3', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Which number shows "twenty"?'),
      answer: ['20'], distractors: ['2', '12', '21']),
  Item(id: 'mi120', skillId: 'ms3', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Which number shows "three"?'),
      answer: ['3'], distractors: ['13', '30', '4']),
  Item(id: 'mi121', skillId: 'ms3', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Which number shows "seventeen"?'),
      answer: ['17'], distractors: ['71', '7', '16']),
  Item(id: 'mi122', skillId: 'ms3', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Which number shows "eleven"?'),
      answer: ['11'], distractors: ['1', '10', '12']),
  Item(id: 'mi123', skillId: 'ms3', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Which number shows "fifteen"?'),
      answer: ['15'], distractors: ['51', '5', '14']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms4 – Before, After, Between
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi124', skillId: 'ms4', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes between 5 and 7?'),
      answer: ['6'], distractors: ['4', '8', '5']),
  Item(id: 'mi125', skillId: 'ms4', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes between 9 and 11?'),
      answer: ['10'], distractors: ['8', '12', '9']),
  Item(id: 'mi126', skillId: 'ms4', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes after 13?'),
      answer: ['14'], distractors: ['12', '15', '11']),
  Item(id: 'mi127', skillId: 'ms4', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes before 9?'),
      answer: ['8'], distractors: ['10', '7', '6']),
  Item(id: 'mi128', skillId: 'ms4', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes between 14 and 16?'),
      answer: ['15'], distractors: ['13', '17', '14']),
  Item(id: 'mi129', skillId: 'ms4', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes between 2 and 4?'),
      answer: ['3'], distractors: ['1', '5', '2']),
  Item(id: 'mi130', skillId: 'ms4', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes after 17?'),
      answer: ['18'], distractors: ['16', '19', '15']),
  Item(id: 'mi131', skillId: 'ms4', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes before 20?'),
      answer: ['19'], distractors: ['18', '17', '16']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms5 – Count to 50  (sequences, what comes after X)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi132', skillId: 'ms5', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 25, 26, 27, ?'),
      answer: ['28'], distractors: ['29', '24', '30']),
  Item(id: 'mi133', skillId: 'ms5', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 39, 40, 41, ?'),
      answer: ['42'], distractors: ['43', '38', '40']),
  Item(id: 'mi134', skillId: 'ms5', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 45, 46, 47, ?'),
      answer: ['48'], distractors: ['49', '44', '50']),
  Item(id: 'mi135', skillId: 'ms5', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 30, 31, 32, ?'),
      answer: ['33'], distractors: ['34', '29', '30']),
  Item(id: 'mi136', skillId: 'ms5', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes after 35?'),
      answer: ['36'], distractors: ['34', '37', '33']),
  Item(id: 'mi137', skillId: 'ms5', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes after 49?'),
      answer: ['50'], distractors: ['48', '47', '46']),
  Item(id: 'mi138', skillId: 'ms5', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 20, 21, 22, ?'),
      answer: ['23'], distractors: ['24', '19', '20']),
  Item(id: 'mi139', skillId: 'ms5', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes before 40?'),
      answer: ['39'], distractors: ['41', '38', '37']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms6 – Count to 100  (sequences in 50-100 range)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi140', skillId: 'ms6', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 55, 56, 57, ?'),
      answer: ['58'], distractors: ['59', '54', '60']),
  Item(id: 'mi141', skillId: 'ms6', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 78, 79, 80, ?'),
      answer: ['81'], distractors: ['82', '77', '90']),
  Item(id: 'mi142', skillId: 'ms6', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 97, 98, 99, ?'),
      answer: ['100'], distractors: ['96', '90', '101']),
  Item(id: 'mi143', skillId: 'ms6', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 60, 61, 62, ?'),
      answer: ['63'], distractors: ['64', '59', '60']),
  Item(id: 'mi144', skillId: 'ms6', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes before 70?'),
      answer: ['69'], distractors: ['71', '68', '67']),
  Item(id: 'mi145', skillId: 'ms6', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 88, 89, 90, ?'),
      answer: ['91'], distractors: ['92', '87', '80']),
  Item(id: 'mi146', skillId: 'ms6', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What number is missing? 50, 60, 70, ?, 90'),
      answer: ['80'], distractors: ['75', '85', '100']),
  Item(id: 'mi147', skillId: 'ms6', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes after 95?'),
      answer: ['96'], distractors: ['94', '97', '93']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms7 – Place Value: Ones and Tens
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi148', skillId: 'ms7', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many tens in 47?'),
      answer: ['4'], distractors: ['7', '47', '3']),
  Item(id: 'mi149', skillId: 'ms7', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many ones in 36?'),
      answer: ['6'], distractors: ['3', '36', '7']),
  Item(id: 'mi150', skillId: 'ms7', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many tens in 82?'),
      answer: ['8'], distractors: ['2', '82', '9']),
  Item(id: 'mi151', skillId: 'ms7', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many ones in 59?'),
      answer: ['9'], distractors: ['5', '59', '8']),
  Item(id: 'mi152', skillId: 'ms7', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many tens in 25?'),
      answer: ['2'], distractors: ['5', '25', '3']),
  Item(id: 'mi153', skillId: 'ms7', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many ones in 71?'),
      answer: ['1'], distractors: ['7', '71', '0']),
  Item(id: 'mi154', skillId: 'ms7', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many tens in 63?'),
      answer: ['6'], distractors: ['3', '63', '7']),
  Item(id: 'mi155', skillId: 'ms7', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many ones in 94?'),
      answer: ['4'], distractors: ['9', '94', '5']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms8 – Skip Counting by 2, 5, 10  (10 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi156', skillId: 'ms8', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Skip count by 2: 2, 4, 6, ?'),
      answer: ['8'], distractors: ['7', '10', '9']),
  Item(id: 'mi157', skillId: 'ms8', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Skip count by 5: 5, 10, 15, ?'),
      answer: ['20'], distractors: ['25', '16', '19']),
  Item(id: 'mi158', skillId: 'ms8', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Skip count by 10: 10, 20, 30, ?'),
      answer: ['40'], distractors: ['50', '31', '35']),
  Item(id: 'mi159', skillId: 'ms8', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Skip count by 2: 10, 12, 14, ?'),
      answer: ['16'], distractors: ['15', '18', '17']),
  Item(id: 'mi160', skillId: 'ms8', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Skip count by 5: 25, 30, 35, ?'),
      answer: ['40'], distractors: ['45', '36', '39']),
  Item(id: 'mi161', skillId: 'ms8', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Skip count by 10: 40, 50, 60, ?'),
      answer: ['70'], distractors: ['80', '61', '65']),
  Item(id: 'mi162', skillId: 'ms8', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Skip count by 2: 18, 20, 22, ?'),
      answer: ['24'], distractors: ['23', '26', '25']),
  Item(id: 'mi163', skillId: 'ms8', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Skip count by 5: 45, 50, 55, ?'),
      answer: ['60'], distractors: ['65', '56', '59']),
  Item(id: 'mi164', skillId: 'ms8', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Skip count by 10: 70, 80, 90, ?'),
      answer: ['100'], distractors: ['91', '95', '99']),
  Item(id: 'mi165', skillId: 'ms8', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Skip count by 2: 6, 8, 10, ?'),
      answer: ['12'], distractors: ['11', '14', '13']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms9 – Count to 200  (numbers 100-200)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi166', skillId: 'ms9', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 100, 101, 102, ?'),
      answer: ['103'], distractors: ['104', '99', '110']),
  Item(id: 'mi167', skillId: 'ms9', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 149, 150, 151, ?'),
      answer: ['152'], distractors: ['153', '148', '160']),
  Item(id: 'mi168', skillId: 'ms9', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 197, 198, 199, ?'),
      answer: ['200'], distractors: ['196', '190', '201']),
  Item(id: 'mi169', skillId: 'ms9', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes before 120?'),
      answer: ['119'], distractors: ['121', '118', '110']),
  Item(id: 'mi170', skillId: 'ms9', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 110, 120, 130, ?'),
      answer: ['140'], distractors: ['150', '131', '135']),
  Item(id: 'mi171', skillId: 'ms9', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes after 175?'),
      answer: ['176'], distractors: ['174', '177', '185']),
  Item(id: 'mi172', skillId: 'ms9', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 160, 170, 180, ?'),
      answer: ['190'], distractors: ['200', '181', '185']),
  Item(id: 'mi173', skillId: 'ms9', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes before 150?'),
      answer: ['149'], distractors: ['151', '148', '140']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms10 – Count to 500  (numbers 200-500)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi174', skillId: 'ms10', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 250, 260, 270, ?'),
      answer: ['280'], distractors: ['290', '271', '275']),
  Item(id: 'mi175', skillId: 'ms10', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 300, 310, 320, ?'),
      answer: ['330'], distractors: ['340', '321', '325']),
  Item(id: 'mi176', skillId: 'ms10', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 400, 410, 420, ?'),
      answer: ['430'], distractors: ['440', '421', '425']),
  Item(id: 'mi177', skillId: 'ms10', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes after 350?'),
      answer: ['351'], distractors: ['349', '360', '340']),
  Item(id: 'mi178', skillId: 'ms10', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 450, 460, 470, ?'),
      answer: ['480'], distractors: ['490', '471', '475']),
  Item(id: 'mi179', skillId: 'ms10', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes before 300?'),
      answer: ['299'], distractors: ['301', '298', '290']),
  Item(id: 'mi180', skillId: 'ms10', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 200, 250, 300, ?'),
      answer: ['350'], distractors: ['400', '301', '310']),
  Item(id: 'mi181', skillId: 'ms10', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 350, 400, 450, ?'),
      answer: ['500'], distractors: ['460', '451', '475']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms11 – Hundreds, Tens, Ones
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi182', skillId: 'ms11', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many hundreds in 345?'),
      answer: ['3'], distractors: ['4', '5', '34']),
  Item(id: 'mi183', skillId: 'ms11', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many tens in 267?'),
      answer: ['6'], distractors: ['2', '7', '26']),
  Item(id: 'mi184', skillId: 'ms11', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many ones in 189?'),
      answer: ['9'], distractors: ['1', '8', '89']),
  Item(id: 'mi185', skillId: 'ms11', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many hundreds in 412?'),
      answer: ['4'], distractors: ['1', '2', '41']),
  Item(id: 'mi186', skillId: 'ms11', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many tens in 350?'),
      answer: ['5'], distractors: ['3', '0', '35']),
  Item(id: 'mi187', skillId: 'ms11', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many ones in 208?'),
      answer: ['8'], distractors: ['2', '0', '20']),
  Item(id: 'mi188', skillId: 'ms11', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many hundreds in 156?'),
      answer: ['1'], distractors: ['5', '6', '15']),
  Item(id: 'mi189', skillId: 'ms11', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many tens in 490?'),
      answer: ['9'], distractors: ['4', '0', '49']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms12 – Reading 3-Digit Numbers
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi190', skillId: 'ms12', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Which number is "two hundred thirty-five"?'),
      answer: ['235'], distractors: ['253', '230', '205']),
  Item(id: 'mi191', skillId: 'ms12', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Which number is "four hundred twelve"?'),
      answer: ['412'], distractors: ['421', '402', '420']),
  Item(id: 'mi192', skillId: 'ms12', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Which number is "three hundred fifty"?'),
      answer: ['350'], distractors: ['305', '355', '530']),
  Item(id: 'mi193', skillId: 'ms12', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Which number is "one hundred nine"?'),
      answer: ['109'], distractors: ['190', '19', '119']),
  Item(id: 'mi194', skillId: 'ms12', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Which number is "two hundred sixty-one"?'),
      answer: ['261'], distractors: ['216', '260', '206']),
  Item(id: 'mi195', skillId: 'ms12', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Which number is "four hundred eighty"?'),
      answer: ['480'], distractors: ['408', '488', '840']),
  Item(id: 'mi196', skillId: 'ms12', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Which number is "one hundred forty-three"?'),
      answer: ['143'], distractors: ['134', '140', '103']),
  Item(id: 'mi197', skillId: 'ms12', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Which number is "three hundred seven"?'),
      answer: ['307'], distractors: ['370', '37', '317']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms13 – Comparing Numbers  (pick_text with > < =)  (10 items)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi198', skillId: 'ms13', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is correct?'),
      answer: ['45 < 54'], distractors: ['45 > 54', '45 = 54']),
  Item(id: 'mi199', skillId: 'ms13', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is correct?'),
      answer: ['87 > 78'], distractors: ['87 < 78', '87 = 78']),
  Item(id: 'mi200', skillId: 'ms13', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is correct?'),
      answer: ['100 > 99'], distractors: ['100 < 99', '100 = 99']),
  Item(id: 'mi201', skillId: 'ms13', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is correct?'),
      answer: ['234 < 243'], distractors: ['234 > 243', '234 = 243']),
  Item(id: 'mi202', skillId: 'ms13', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is correct?'),
      answer: ['50 = 50'], distractors: ['50 > 50', '50 < 50']),
  Item(id: 'mi203', skillId: 'ms13', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is correct?'),
      answer: ['301 > 299'], distractors: ['301 < 299', '301 = 299']),
  Item(id: 'mi204', skillId: 'ms13', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is correct?'),
      answer: ['156 < 165'], distractors: ['156 > 165', '156 = 165']),
  Item(id: 'mi205', skillId: 'ms13', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is correct?'),
      answer: ['420 > 402'], distractors: ['420 < 402', '420 = 402']),
  Item(id: 'mi206', skillId: 'ms13', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is correct?'),
      answer: ['75 < 85'], distractors: ['75 > 85', '75 = 85']),
  Item(id: 'mi207', skillId: 'ms13', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is correct?'),
      answer: ['99 < 100'], distractors: ['99 > 100', '99 = 100']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms14 – Add within 10
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi208', skillId: 'ms14', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '3 + 4 = ?'),
      answer: ['7'], distractors: ['6', '8', '5']),
  Item(id: 'mi209', skillId: 'ms14', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '2 + 6 = ?'),
      answer: ['8'], distractors: ['7', '9', '4']),
  Item(id: 'mi210', skillId: 'ms14', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '1 + 5 = ?'),
      answer: ['6'], distractors: ['5', '7', '4']),
  Item(id: 'mi211', skillId: 'ms14', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '6 + 2 = ?'),
      answer: ['8'], distractors: ['9', '7', '4']),
  Item(id: 'mi212', skillId: 'ms14', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '5 + 4 = ?'),
      answer: ['9'], distractors: ['8', '10', '7']),
  Item(id: 'mi213', skillId: 'ms14', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '7 + 1 = ?'),
      answer: ['8'], distractors: ['9', '7', '6']),
  Item(id: 'mi214', skillId: 'ms14', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '9 + 1 = ?'),
      answer: ['10'], distractors: ['9', '8', '11']),
  Item(id: 'mi215', skillId: 'ms14', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '3 + 6 = ?'),
      answer: ['9'], distractors: ['8', '10', '7']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms15 – Add within 20
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi216', skillId: 'ms15', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '8 + 7 = ?'),
      answer: ['15'], distractors: ['14', '16', '13']),
  Item(id: 'mi217', skillId: 'ms15', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '9 + 6 = ?'),
      answer: ['15'], distractors: ['14', '16', '13']),
  Item(id: 'mi218', skillId: 'ms15', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '8 + 6 = ?'),
      answer: ['14'], distractors: ['13', '15', '12']),
  Item(id: 'mi219', skillId: 'ms15', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '7 + 7 = ?'),
      answer: ['14'], distractors: ['13', '15', '12']),
  Item(id: 'mi220', skillId: 'ms15', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '9 + 8 = ?'),
      answer: ['17'], distractors: ['16', '18', '15']),
  Item(id: 'mi221', skillId: 'ms15', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '9 + 9 = ?'),
      answer: ['18'], distractors: ['17', '19', '16']),
  Item(id: 'mi222', skillId: 'ms15', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '8 + 8 = ?'),
      answer: ['16'], distractors: ['15', '17', '14']),
  Item(id: 'mi223', skillId: 'ms15', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '7 + 6 = ?'),
      answer: ['13'], distractors: ['12', '14', '11']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms16 – Add 2-Digit (No Carry)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi224', skillId: 'ms16', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '23 + 14 = ?'),
      answer: ['37'], distractors: ['36', '38', '27']),
  Item(id: 'mi225', skillId: 'ms16', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '41 + 25 = ?'),
      answer: ['66'], distractors: ['65', '67', '56']),
  Item(id: 'mi226', skillId: 'ms16', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '32 + 15 = ?'),
      answer: ['47'], distractors: ['46', '48', '37']),
  Item(id: 'mi227', skillId: 'ms16', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '50 + 27 = ?'),
      answer: ['77'], distractors: ['76', '78', '67']),
  Item(id: 'mi228', skillId: 'ms16', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '36 + 21 = ?'),
      answer: ['57'], distractors: ['56', '58', '47']),
  Item(id: 'mi229', skillId: 'ms16', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '44 + 33 = ?'),
      answer: ['77'], distractors: ['76', '78', '67']),
  Item(id: 'mi230', skillId: 'ms16', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '25 + 13 = ?'),
      answer: ['38'], distractors: ['37', '39', '28']),
  Item(id: 'mi231', skillId: 'ms16', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '62 + 17 = ?'),
      answer: ['79'], distractors: ['78', '80', '69']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms17 – Add 2-Digit (With Carry)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi232', skillId: 'ms17', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '47 + 38 = ?'),
      answer: ['85'], distractors: ['84', '86', '75']),
  Item(id: 'mi233', skillId: 'ms17', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '56 + 29 = ?'),
      answer: ['85'], distractors: ['84', '86', '75']),
  Item(id: 'mi234', skillId: 'ms17', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '28 + 47 = ?'),
      answer: ['75'], distractors: ['74', '76', '65']),
  Item(id: 'mi235', skillId: 'ms17', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '63 + 19 = ?'),
      answer: ['82'], distractors: ['81', '83', '72']),
  Item(id: 'mi236', skillId: 'ms17', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '75 + 18 = ?'),
      answer: ['93'], distractors: ['92', '94', '83']),
  Item(id: 'mi237', skillId: 'ms17', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '39 + 45 = ?'),
      answer: ['84'], distractors: ['83', '85', '74']),
  Item(id: 'mi238', skillId: 'ms17', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '58 + 27 = ?'),
      answer: ['85'], distractors: ['84', '86', '75']),
  Item(id: 'mi239', skillId: 'ms17', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '44 + 38 = ?'),
      answer: ['82'], distractors: ['81', '83', '72']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms18 – Subtract within 10
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi240', skillId: 'ms18', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '8 - 3 = ?'),
      answer: ['5'], distractors: ['4', '6', '11']),
  Item(id: 'mi241', skillId: 'ms18', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '7 - 5 = ?'),
      answer: ['2'], distractors: ['3', '1', '12']),
  Item(id: 'mi242', skillId: 'ms18', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '10 - 4 = ?'),
      answer: ['6'], distractors: ['5', '7', '14']),
  Item(id: 'mi243', skillId: 'ms18', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '9 - 6 = ?'),
      answer: ['3'], distractors: ['2', '4', '15']),
  Item(id: 'mi244', skillId: 'ms18', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '6 - 2 = ?'),
      answer: ['4'], distractors: ['3', '5', '8']),
  Item(id: 'mi245', skillId: 'ms18', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '10 - 7 = ?'),
      answer: ['3'], distractors: ['2', '4', '17']),
  Item(id: 'mi246', skillId: 'ms18', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '8 - 5 = ?'),
      answer: ['3'], distractors: ['2', '4', '13']),
  Item(id: 'mi247', skillId: 'ms18', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '9 - 4 = ?'),
      answer: ['5'], distractors: ['4', '6', '13']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms19 – Subtract within 20
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi248', skillId: 'ms19', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '15 - 8 = ?'),
      answer: ['7'], distractors: ['6', '8', '23']),
  Item(id: 'mi249', skillId: 'ms19', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '18 - 9 = ?'),
      answer: ['9'], distractors: ['8', '10', '27']),
  Item(id: 'mi250', skillId: 'ms19', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '14 - 7 = ?'),
      answer: ['7'], distractors: ['6', '8', '21']),
  Item(id: 'mi251', skillId: 'ms19', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '16 - 9 = ?'),
      answer: ['7'], distractors: ['6', '8', '25']),
  Item(id: 'mi252', skillId: 'ms19', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '13 - 6 = ?'),
      answer: ['7'], distractors: ['6', '8', '19']),
  Item(id: 'mi253', skillId: 'ms19', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '17 - 8 = ?'),
      answer: ['9'], distractors: ['8', '10', '25']),
  Item(id: 'mi254', skillId: 'ms19', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '12 - 5 = ?'),
      answer: ['7'], distractors: ['6', '8', '17']),
  Item(id: 'mi255', skillId: 'ms19', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '20 - 9 = ?'),
      answer: ['11'], distractors: ['10', '12', '29']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms20 – Subtract 2-Digit (No Borrow)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi256', skillId: 'ms20', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '48 - 23 = ?'),
      answer: ['25'], distractors: ['24', '26', '71']),
  Item(id: 'mi257', skillId: 'ms20', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '67 - 35 = ?'),
      answer: ['32'], distractors: ['31', '33', '102']),
  Item(id: 'mi258', skillId: 'ms20', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '89 - 47 = ?'),
      answer: ['42'], distractors: ['41', '43', '136']),
  Item(id: 'mi259', skillId: 'ms20', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '76 - 54 = ?'),
      answer: ['22'], distractors: ['21', '23', '130']),
  Item(id: 'mi260', skillId: 'ms20', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '95 - 63 = ?'),
      answer: ['32'], distractors: ['31', '33', '158']),
  Item(id: 'mi261', skillId: 'ms20', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '58 - 26 = ?'),
      answer: ['32'], distractors: ['31', '33', '84']),
  Item(id: 'mi262', skillId: 'ms20', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '64 - 31 = ?'),
      answer: ['33'], distractors: ['32', '34', '95']),
  Item(id: 'mi263', skillId: 'ms20', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '87 - 45 = ?'),
      answer: ['42'], distractors: ['41', '43', '132']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms21 – Subtract 2-Digit (With Borrow)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi264', skillId: 'ms21', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '52 - 37 = ?'),
      answer: ['15'], distractors: ['14', '16', '89']),
  Item(id: 'mi265', skillId: 'ms21', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '61 - 48 = ?'),
      answer: ['13'], distractors: ['12', '14', '109']),
  Item(id: 'mi266', skillId: 'ms21', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '43 - 28 = ?'),
      answer: ['15'], distractors: ['14', '16', '71']),
  Item(id: 'mi267', skillId: 'ms21', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '70 - 35 = ?'),
      answer: ['35'], distractors: ['34', '36', '105']),
  Item(id: 'mi268', skillId: 'ms21', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '54 - 29 = ?'),
      answer: ['25'], distractors: ['24', '26', '83']),
  Item(id: 'mi269', skillId: 'ms21', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '81 - 56 = ?'),
      answer: ['25'], distractors: ['24', '26', '137']),
  Item(id: 'mi270', skillId: 'ms21', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '31 - 18 = ?'),
      answer: ['13'], distractors: ['12', '14', '49']),
  Item(id: 'mi271', skillId: 'ms21', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '42 - 27 = ?'),
      answer: ['15'], distractors: ['14', '16', '69']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms22 – 2D Shapes
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi272', skillId: 'ms22', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many sides does a triangle have?'),
      answer: ['3'], distractors: ['4', '2', '5']),
  Item(id: 'mi273', skillId: 'ms22', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many sides does a square have?'),
      answer: ['4'], distractors: ['3', '5', '6']),
  Item(id: 'mi274', skillId: 'ms22', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many corners does a rectangle have?'),
      answer: ['4'], distractors: ['3', '5', '2']),
  Item(id: 'mi275', skillId: 'ms22', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many sides does a pentagon have?'),
      answer: ['5'], distractors: ['4', '6', '3']),
  Item(id: 'mi276', skillId: 'ms22', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many sides does a hexagon have?'),
      answer: ['6'], distractors: ['5', '4', '8']),
  Item(id: 'mi277', skillId: 'ms22', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many corners does a triangle have?'),
      answer: ['3'], distractors: ['4', '2', '1']),
  Item(id: 'mi278', skillId: 'ms22', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which shape has no corners?'),
      answer: ['Circle'], distractors: ['Square', 'Triangle', 'Rectangle']),
  Item(id: 'mi279', skillId: 'ms22', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many sides does a square and a triangle have altogether?'),
      answer: ['7'], distractors: ['6', '8', '5']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms23 – 3D Shapes
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi280', skillId: 'ms23', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which shape looks like a ball?'),
      answer: ['Sphere'], distractors: ['Cube', 'Cylinder', 'Cone']),
  Item(id: 'mi281', skillId: 'ms23', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which shape looks like a box?'),
      answer: ['Cube'], distractors: ['Sphere', 'Cone', 'Cylinder']),
  Item(id: 'mi282', skillId: 'ms23', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which shape looks like a can?'),
      answer: ['Cylinder'], distractors: ['Sphere', 'Cube', 'Cone']),
  Item(id: 'mi283', skillId: 'ms23', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which shape looks like a party hat?'),
      answer: ['Cone'], distractors: ['Cylinder', 'Sphere', 'Cube']),
  Item(id: 'mi284', skillId: 'ms23', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many faces does a cube have?'),
      answer: ['6'], distractors: ['4', '8', '5']),
  Item(id: 'mi285', skillId: 'ms23', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many edges does a cube have?'),
      answer: ['12'], distractors: ['8', '6', '10']),
  Item(id: 'mi286', skillId: 'ms23', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many corners does a cube have?'),
      answer: ['8'], distractors: ['6', '4', '12']),
  Item(id: 'mi287', skillId: 'ms23', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'A dice is shaped like a ___'),
      answer: ['Cube'], distractors: ['Sphere', 'Cylinder', 'Cone']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms24 – Patterns
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi288', skillId: 'ms24', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What comes next? 🔴🔵🔴🔵🔴?'),
      answer: ['🔵'], distractors: ['🔴', '🟢', '🟡']),
  Item(id: 'mi289', skillId: 'ms24', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What comes next? 🌟🌙🌟🌙🌟?'),
      answer: ['🌙'], distractors: ['🌟', '☀️', '⭐']),
  Item(id: 'mi290', skillId: 'ms24', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What comes next? ▲●▲●▲?'),
      answer: ['●'], distractors: ['▲', '■', '◆']),
  Item(id: 'mi291', skillId: 'ms24', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What comes next? 🔺🔻🔺🔻🔺?'),
      answer: ['🔻'], distractors: ['🔺', '⬛', '🔶']),
  Item(id: 'mi292', skillId: 'ms24', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 2, 4, 6, 8, ?'),
      answer: ['10'], distractors: ['9', '12', '11']),
  Item(id: 'mi293', skillId: 'ms24', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 1, 3, 5, 7, ?'),
      answer: ['9'], distractors: ['8', '10', '11']),
  Item(id: 'mi294', skillId: 'ms24', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What comes next? 🟥🟥🟦🟥🟥?'),
      answer: ['🟦'], distractors: ['🟥', '🟨', '🟩']),
  Item(id: 'mi295', skillId: 'ms24', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What comes next? big, small, big, small, big?'),
      answer: ['small'], distractors: ['big', 'medium', 'tiny']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms25 – Big and Small
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi296', skillId: 'ms25', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is bigger?'),
      answer: ['🐘 Elephant'], distractors: ['🐭 Mouse', '🐜 Ant', '🐛 Bug']),
  Item(id: 'mi297', skillId: 'ms25', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is smaller?'),
      answer: ['🍎 Apple'], distractors: ['🍉 Watermelon', '🎃 Pumpkin', '⚽ Ball']),
  Item(id: 'mi298', skillId: 'ms25', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is bigger?'),
      answer: ['🏠 House'], distractors: ['📦 Box', '🎒 Bag', '🧸 Teddy']),
  Item(id: 'mi299', skillId: 'ms25', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is smaller?'),
      answer: ['🐜 Ant'], distractors: ['🐘 Elephant', '🐕 Dog', '🐈 Cat']),
  Item(id: 'mi300', skillId: 'ms25', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which holds more water?'),
      answer: ['🪣 Bucket'], distractors: ['☕ Cup', '🥄 Spoon', '🥤 Glass']),
  Item(id: 'mi301', skillId: 'ms25', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is longer?'),
      answer: ['🚂 Train'], distractors: ['🚗 Car', '🚲 Bike', '🛴 Scooter']),
  Item(id: 'mi302', skillId: 'ms25', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is bigger?'),
      answer: ['🌍 Earth'], distractors: ['🌙 Moon', '⚽ Ball', '🍊 Orange']),
  Item(id: 'mi303', skillId: 'ms25', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is smaller?'),
      answer: ['✏️ Pencil'], distractors: ['🏫 School', '🌳 Tree', '🚗 Car']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms26 – Tall and Short
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi304', skillId: 'ms26', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is taller?'),
      answer: ['🌳 Tree'], distractors: ['🌷 Flower', '🌿 Grass', '🍄 Mushroom']),
  Item(id: 'mi305', skillId: 'ms26', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is shorter?'),
      answer: ['🖍️ Crayon'], distractors: ['📏 Ruler', '✏️ Pencil', '🗡️ Sword']),
  Item(id: 'mi306', skillId: 'ms26', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is taller?'),
      answer: ['🏢 Building'], distractors: ['🏠 House', '⛺ Tent', '🛖 Hut']),
  Item(id: 'mi307', skillId: 'ms26', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is shorter?'),
      answer: ['👶 Baby'], distractors: ['👨 Dad', '👩 Mom', '🧑 Teen']),
  Item(id: 'mi308', skillId: 'ms26', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is taller?'),
      answer: ['🦒 Giraffe'], distractors: ['🐕 Dog', '🐈 Cat', '🐢 Turtle']),
  Item(id: 'mi309', skillId: 'ms26', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is shorter?'),
      answer: ['🐢 Turtle'], distractors: ['🦒 Giraffe', '🐘 Elephant', '🐕 Dog']),
  Item(id: 'mi310', skillId: 'ms26', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is taller?'),
      answer: ['🌻 Sunflower'], distractors: ['🌱 Seedling', '🌿 Grass', '🍀 Clover']),
  Item(id: 'mi311', skillId: 'ms26', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is shorter?'),
      answer: ['🕯️ Candle'], distractors: ['🏢 Building', '🌳 Tree', '🚪 Door']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms27 – Heavy and Light
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi312', skillId: 'ms27', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is heavier?'),
      answer: ['📚 Book'], distractors: ['🪶 Feather', '🍂 Leaf', '🧻 Tissue']),
  Item(id: 'mi313', skillId: 'ms27', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is lighter?'),
      answer: ['🎈 Balloon'], distractors: ['🪨 Rock', '🧱 Brick', '📚 Book']),
  Item(id: 'mi314', skillId: 'ms27', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is heavier?'),
      answer: ['🪨 Rock'], distractors: ['🍂 Leaf', '🪶 Feather', '🧻 Tissue']),
  Item(id: 'mi315', skillId: 'ms27', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is lighter?'),
      answer: ['🪶 Feather'], distractors: ['📚 Book', '🍎 Apple', '🪨 Rock']),
  Item(id: 'mi316', skillId: 'ms27', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is heavier?'),
      answer: ['🚗 Car'], distractors: ['🚲 Bicycle', '🛴 Scooter', '🛹 Skateboard']),
  Item(id: 'mi317', skillId: 'ms27', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is lighter?'),
      answer: ['🍎 Apple'], distractors: ['🍉 Watermelon', '🎃 Pumpkin', '🪨 Rock']),
  Item(id: 'mi318', skillId: 'ms27', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is heavier?'),
      answer: ['⚽ Football'], distractors: ['🎈 Balloon', '🪶 Feather', '🍂 Leaf']),
  Item(id: 'mi319', skillId: 'ms27', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is lighter?'),
      answer: ['🧸 Teddy bear'], distractors: ['🪑 Chair', '🛏️ Bed', '📺 TV']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms28 – Days of the Week
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi320', skillId: 'ms28', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What day comes after Monday?'),
      answer: ['Tuesday'], distractors: ['Wednesday', 'Sunday', 'Friday']),
  Item(id: 'mi321', skillId: 'ms28', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What day comes before Friday?'),
      answer: ['Thursday'], distractors: ['Wednesday', 'Saturday', 'Monday']),
  Item(id: 'mi322', skillId: 'ms28', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What day comes after Wednesday?'),
      answer: ['Thursday'], distractors: ['Tuesday', 'Friday', 'Monday']),
  Item(id: 'mi323', skillId: 'ms28', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What day comes before Monday?'),
      answer: ['Sunday'], distractors: ['Tuesday', 'Saturday', 'Friday']),
  Item(id: 'mi324', skillId: 'ms28', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What day comes after Saturday?'),
      answer: ['Sunday'], distractors: ['Monday', 'Friday', 'Tuesday']),
  Item(id: 'mi325', skillId: 'ms28', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What day comes after Thursday?'),
      answer: ['Friday'], distractors: ['Wednesday', 'Saturday', 'Monday']),
  Item(id: 'mi326', skillId: 'ms28', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many days are in a week?'),
      answer: ['7'], distractors: ['5', '6', '8']),
  Item(id: 'mi327', skillId: 'ms28', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'What day comes before Wednesday?'),
      answer: ['Tuesday'], distractors: ['Monday', 'Thursday', 'Sunday']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms29 – Reading Clock (Hours)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi328', skillId: 'ms29', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'The hour hand points to 3. What time is it?'),
      answer: ['3 o\'clock'], distractors: ['6 o\'clock', '12 o\'clock', '9 o\'clock']),
  Item(id: 'mi329', skillId: 'ms29', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'The hour hand points to 7. What time is it?'),
      answer: ['7 o\'clock'], distractors: ['5 o\'clock', '11 o\'clock', '2 o\'clock']),
  Item(id: 'mi330', skillId: 'ms29', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'The hour hand points to 12. What time is it?'),
      answer: ['12 o\'clock'], distractors: ['6 o\'clock', '1 o\'clock', '10 o\'clock']),
  Item(id: 'mi331', skillId: 'ms29', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'The hour hand points to 5. What time is it?'),
      answer: ['5 o\'clock'], distractors: ['10 o\'clock', '3 o\'clock', '7 o\'clock']),
  Item(id: 'mi332', skillId: 'ms29', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'The hour hand points to 9. What time is it?'),
      answer: ['9 o\'clock'], distractors: ['3 o\'clock', '6 o\'clock', '12 o\'clock']),
  Item(id: 'mi333', skillId: 'ms29', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'The hour hand points to 1. What time is it?'),
      answer: ['1 o\'clock'], distractors: ['11 o\'clock', '10 o\'clock', '7 o\'clock']),
  Item(id: 'mi334', skillId: 'ms29', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'The hour hand points to 6. What time is it?'),
      answer: ['6 o\'clock'], distractors: ['12 o\'clock', '9 o\'clock', '3 o\'clock']),
  Item(id: 'mi335', skillId: 'ms29', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'The hour hand points to 10. What time is it?'),
      answer: ['10 o\'clock'], distractors: ['2 o\'clock', '5 o\'clock', '8 o\'clock']),

  // ═══════════════════════════════════════════════════════════════════════════
  // ms30 – Coins & Money
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi336', skillId: 'ms30', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many cents is one quarter?'),
      answer: ['25'], distractors: ['10', '5', '50']),
  Item(id: 'mi337', skillId: 'ms30', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many cents is one penny?'),
      answer: ['1'], distractors: ['5', '10', '25']),
  Item(id: 'mi338', skillId: 'ms30', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many cents is one nickel?'),
      answer: ['5'], distractors: ['1', '10', '25']),
  Item(id: 'mi339', skillId: 'ms30', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'How many cents is one dime?'),
      answer: ['10'], distractors: ['5', '25', '1']),
  Item(id: 'mi340', skillId: 'ms30', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'You have 2 nickels. How many cents?'),
      answer: ['10'], distractors: ['5', '15', '25']),
  Item(id: 'mi341', skillId: 'ms30', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'You have 3 dimes. How many cents?'),
      answer: ['30'], distractors: ['20', '25', '35']),
  Item(id: 'mi342', skillId: 'ms30', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which coin is worth the MOST?'),
      answer: ['Quarter'], distractors: ['Dime', 'Nickel', 'Penny']),
  Item(id: 'mi343', skillId: 'ms30', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'You have 1 quarter and 2 pennies. How many cents?'),
      answer: ['27'], distractors: ['26', '28', '22']),

  // ═══════════════════════════════════════════════════════════════════════════
  // M9 – Number Sense & Ordering (ms31-ms35)
  // M10 – Addition & Subtraction Mastery (ms36-ms40)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi344', skillId: 'ms31', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '1 + ___ = 10'),
      answer: ['9'], distractors: ['8', '10', '7']),
  Item(id: 'mi345', skillId: 'ms31', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '2 + ___ = 10'),
      answer: ['8'], distractors: ['7', '9', '10']),
  Item(id: 'mi346', skillId: 'ms31', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '3 + ___ = 10'),
      answer: ['7'], distractors: ['6', '8', '9']),
  Item(id: 'mi347', skillId: 'ms31', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '4 + ___ = 10'),
      answer: ['6'], distractors: ['5', '7', '8']),
  Item(id: 'mi348', skillId: 'ms31', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '5 + ___ = 10'),
      answer: ['5'], distractors: ['4', '6', '7']),
  Item(id: 'mi349', skillId: 'ms31', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '6 + ___ = 10'),
      answer: ['4'], distractors: ['3', '5', '6']),
  Item(id: 'mi350', skillId: 'ms31', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '7 + ___ = 10'),
      answer: ['3'], distractors: ['2', '4', '5']),
  Item(id: 'mi351', skillId: 'ms31', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '___ + 2 = 10'),
      answer: ['8'], distractors: ['7', '9', '10']),
  Item(id: 'mi352', skillId: 'ms31', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '___ + 1 = 10'),
      answer: ['9'], distractors: ['8', '10', '7']),
  Item(id: 'mi353', skillId: 'ms31', exerciseType: ExerciseType.match_pairs,
      prompt: ItemPrompt(text: 'Match the number bonds that make 10'),
      answer: ['1+9', '2+8', '3+7', '4+6', '5+5'], distractors: ['1+8', '2+9', '3+6', '4+7', '2+7']),
  Item(id: 'mi354', skillId: 'ms32', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '10 + ___ = 20'),
      answer: ['10'], distractors: ['9', '11', '8']),
  Item(id: 'mi355', skillId: 'ms32', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '12 + ___ = 20'),
      answer: ['8'], distractors: ['7', '9', '6']),
  Item(id: 'mi356', skillId: 'ms32', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '15 + ___ = 20'),
      answer: ['5'], distractors: ['4', '6', '3']),
  Item(id: 'mi357', skillId: 'ms32', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '13 + ___ = 20'),
      answer: ['7'], distractors: ['6', '8', '5']),
  Item(id: 'mi358', skillId: 'ms32', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '11 + ___ = 20'),
      answer: ['9'], distractors: ['8', '10', '7']),
  Item(id: 'mi359', skillId: 'ms32', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '14 + ___ = 20'),
      answer: ['6'], distractors: ['5', '7', '4']),
  Item(id: 'mi360', skillId: 'ms32', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '16 + ___ = 20'),
      answer: ['4'], distractors: ['3', '5', '2']),
  Item(id: 'mi361', skillId: 'ms32', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '17 + ___ = 20'),
      answer: ['3'], distractors: ['2', '4', '1']),
  Item(id: 'mi362', skillId: 'ms32', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '___ + 2 = 20'),
      answer: ['18'], distractors: ['17', '19', '16']),
  Item(id: 'mi363', skillId: 'ms32', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '___ + 1 = 20'),
      answer: ['19'], distractors: ['18', '20', '17']),
  Item(id: 'mi364', skillId: 'ms33', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which shows numbers in ASCENDING order?'),
      answer: ['3, 7, 12, 15, 20'], distractors: ['20, 15, 12, 7, 3', '12, 3, 20, 7, 15', '15, 7, 3, 20, 12']),
  Item(id: 'mi365', skillId: 'ms33', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which shows numbers in DESCENDING order?'),
      answer: ['18, 14, 10, 6, 2'], distractors: ['2, 6, 10, 14, 18', '10, 18, 6, 2, 14', '14, 2, 18, 6, 10']),
  Item(id: 'mi366', skillId: 'ms33', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Put in ascending order: 8, 3, 15, 1'),
      answer: ['1, 3, 8, 15'], distractors: ['15, 8, 3, 1', '3, 1, 15, 8', '8, 15, 1, 3']),
  Item(id: 'mi367', skillId: 'ms33', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Put in descending order: 5, 19, 11, 7'),
      answer: ['19, 11, 7, 5'], distractors: ['5, 7, 11, 19', '7, 5, 19, 11', '11, 19, 5, 7']),
  Item(id: 'mi368', skillId: 'ms33', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is correct ascending order?'),
      answer: ['2, 5, 9, 13, 17'], distractors: ['17, 13, 9, 5, 2', '9, 2, 17, 5, 13', '13, 5, 2, 17, 9']),
  Item(id: 'mi369', skillId: 'ms33', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Count backwards from 20. What comes after 20, 19, 18?'),
      answer: ['17'], distractors: ['16', '15', '19']),
  Item(id: 'mi370', skillId: 'ms33', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Count backwards: 15, 14, 13, __?'),
      answer: ['12'], distractors: ['11', '16', '10']),
  Item(id: 'mi371', skillId: 'ms33', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which list goes from SMALLEST to BIGGEST?'),
      answer: ['4, 8, 12, 16'], distractors: ['16, 12, 8, 4', '8, 4, 16, 12', '12, 16, 4, 8']),
  Item(id: 'mi372', skillId: 'ms33', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Count backwards from 10: 10, 9, 8, 7, __?'),
      answer: ['6'], distractors: ['5', '11', '3']),
  Item(id: 'mi373', skillId: 'ms33', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Descending order from 20: 20, 18, 16, __?'),
      answer: ['14'], distractors: ['12', '15', '13']),
  Item(id: 'mi374', skillId: 'ms34', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What number is missing? 1, 2, __, 4, 5'),
      answer: ['3'], distractors: ['6', '0', '7']),
  Item(id: 'mi375', skillId: 'ms34', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What number is missing? 6, 7, 8, __, 10'),
      answer: ['9'], distractors: ['11', '5', '12']),
  Item(id: 'mi376', skillId: 'ms34', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What number is missing? 11, 12, __, 14, 15'),
      answer: ['13'], distractors: ['16', '10', '17']),
  Item(id: 'mi377', skillId: 'ms34', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What number is missing? 3, 6, __, 12, 15'),
      answer: ['9'], distractors: ['8', '10', '7']),
  Item(id: 'mi378', skillId: 'ms34', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What number is missing? 2, 4, 6, __, 10'),
      answer: ['8'], distractors: ['7', '9', '12']),
  Item(id: 'mi379', skillId: 'ms34', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What number is missing? 20, 18, __, 14, 12'),
      answer: ['16'], distractors: ['15', '10', '17']),
  Item(id: 'mi380', skillId: 'ms34', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What number is missing? 5, 10, __, 20'),
      answer: ['15'], distractors: ['12', '25', '8']),
  Item(id: 'mi381', skillId: 'ms34', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes next? 16, 17, 18, 19, __'),
      answer: ['20'], distractors: ['15', '21', '10']),
  Item(id: 'mi382', skillId: 'ms34', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What number is missing? 1, 3, 5, __, 9'),
      answer: ['7'], distractors: ['6', '8', '4']),
  Item(id: 'mi383', skillId: 'ms34', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What number is missing? 10, __, 6, 4, 2'),
      answer: ['8'], distractors: ['7', '9', '5']),
  Item(id: 'mi384', skillId: 'ms35', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Start at 5. Count on 1. What number?'),
      answer: ['6'], distractors: ['4', '7', '5']),
  Item(id: 'mi385', skillId: 'ms35', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Start at 8. Count on 1. What number?'),
      answer: ['9'], distractors: ['7', '10', '8']),
  Item(id: 'mi386', skillId: 'ms35', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Start at 12. Count on 1. What number?'),
      answer: ['13'], distractors: ['11', '14', '12']),
  Item(id: 'mi387', skillId: 'ms35', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Start at 3. Count on 3. What number?'),
      answer: ['6'], distractors: ['5', '7', '4']),
  Item(id: 'mi388', skillId: 'ms35', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Start at 7. Count on 2. What number?'),
      answer: ['9'], distractors: ['8', '10', '5']),
  Item(id: 'mi389', skillId: 'ms35', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Start at 14. Count on 1. What number?'),
      answer: ['15'], distractors: ['13', '16', '14']),
  Item(id: 'mi390', skillId: 'ms35', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Start at 9. Count on 4. What number?'),
      answer: ['13'], distractors: ['12', '14', '11']),
  Item(id: 'mi391', skillId: 'ms35', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Start at 6. Count on 5. What number?'),
      answer: ['11'], distractors: ['10', '12', '9']),
  Item(id: 'mi392', skillId: 'ms35', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Start at 11. Count on 3. What number?'),
      answer: ['14'], distractors: ['13', '15', '12']),
  Item(id: 'mi393', skillId: 'ms35', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Start at 4. Count on 6. What number?'),
      answer: ['10'], distractors: ['9', '11', '8']),
  Item(id: 'mi394', skillId: 'ms36', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '1 + 1 = ?'),
      answer: ['2'], distractors: ['1', '3', '0']),
  Item(id: 'mi395', skillId: 'ms36', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '2 + 3 = ?'),
      answer: ['5'], distractors: ['4', '6', '3']),
  Item(id: 'mi396', skillId: 'ms36', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '3 + 4 = ?'),
      answer: ['7'], distractors: ['6', '8', '5']),
  Item(id: 'mi397', skillId: 'ms36', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '4 + 5 = ?'),
      answer: ['9'], distractors: ['8', '10', '7']),
  Item(id: 'mi398', skillId: 'ms36', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '1 + 6 = ?'),
      answer: ['7'], distractors: ['6', '8', '5']),
  Item(id: 'mi399', skillId: 'ms36', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '2 + 8 = ?'),
      answer: ['10'], distractors: ['9', '11', '8']),
  Item(id: 'mi400', skillId: 'ms36', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '3 + 2 = ?'),
      answer: ['5'], distractors: ['4', '6', '3']),
  Item(id: 'mi401', skillId: 'ms36', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '5 + 4 = ?'),
      answer: ['9'], distractors: ['8', '10', '7']),
  Item(id: 'mi402', skillId: 'ms36', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '6 + 3 = ?'),
      answer: ['9'], distractors: ['8', '10', '7']),
  Item(id: 'mi403', skillId: 'ms36', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '7 + 2 = ?'),
      answer: ['9'], distractors: ['8', '10', '7']),
  Item(id: 'mi404', skillId: 'ms36', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '4 + 4 = ?'),
      answer: ['8'], distractors: ['7', '9', '6']),
  Item(id: 'mi405', skillId: 'ms36', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '1 + 9 = ?'),
      answer: ['10'], distractors: ['9', '11', '8']),
  Item(id: 'mi406', skillId: 'ms37', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '5 + 6 = ?'),
      answer: ['11'], distractors: ['10', '12', '9']),
  Item(id: 'mi407', skillId: 'ms37', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '7 + 5 = ?'),
      answer: ['12'], distractors: ['11', '13', '10']),
  Item(id: 'mi408', skillId: 'ms37', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '8 + 5 = ?'),
      answer: ['13'], distractors: ['12', '14', '11']),
  Item(id: 'mi409', skillId: 'ms37', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '6 + 8 = ?'),
      answer: ['14'], distractors: ['13', '15', '12']),
  Item(id: 'mi410', skillId: 'ms37', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '7 + 8 = ?'),
      answer: ['15'], distractors: ['14', '16', '13']),
  Item(id: 'mi411', skillId: 'ms37', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '9 + 7 = ?'),
      answer: ['16'], distractors: ['15', '17', '14']),
  Item(id: 'mi412', skillId: 'ms37', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '8 + 9 = ?'),
      answer: ['17'], distractors: ['16', '18', '15']),
  Item(id: 'mi413', skillId: 'ms37', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '9 + 9 = ?'),
      answer: ['18'], distractors: ['17', '19', '16']),
  Item(id: 'mi414', skillId: 'ms37', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '10 + 9 = ?'),
      answer: ['19'], distractors: ['18', '20', '17']),
  Item(id: 'mi415', skillId: 'ms37', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '10 + 10 = ?'),
      answer: ['20'], distractors: ['19', '18', '17']),
  Item(id: 'mi416', skillId: 'ms37', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '6 + 7 = ?'),
      answer: ['13'], distractors: ['12', '14', '11']),
  Item(id: 'mi417', skillId: 'ms37', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '8 + 6 = ?'),
      answer: ['14'], distractors: ['13', '15', '12']),
  Item(id: 'mi418', skillId: 'ms38', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '3 - 1 = ?'),
      answer: ['2'], distractors: ['1', '3', '4']),
  Item(id: 'mi419', skillId: 'ms38', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '5 - 2 = ?'),
      answer: ['3'], distractors: ['2', '4', '5']),
  Item(id: 'mi420', skillId: 'ms38', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '7 - 4 = ?'),
      answer: ['3'], distractors: ['2', '4', '5']),
  Item(id: 'mi421', skillId: 'ms38', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '9 - 3 = ?'),
      answer: ['6'], distractors: ['5', '7', '8']),
  Item(id: 'mi422', skillId: 'ms38', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '8 - 5 = ?'),
      answer: ['3'], distractors: ['2', '4', '5']),
  Item(id: 'mi423', skillId: 'ms38', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '6 - 4 = ?'),
      answer: ['2'], distractors: ['1', '3', '4']),
  Item(id: 'mi424', skillId: 'ms38', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '10 - 7 = ?'),
      answer: ['3'], distractors: ['2', '4', '5']),
  Item(id: 'mi425', skillId: 'ms38', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '4 - 1 = ?'),
      answer: ['3'], distractors: ['2', '4', '5']),
  Item(id: 'mi426', skillId: 'ms38', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '9 - 6 = ?'),
      answer: ['3'], distractors: ['2', '4', '5']),
  Item(id: 'mi427', skillId: 'ms38', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '7 - 2 = ?'),
      answer: ['5'], distractors: ['4', '6', '7']),
  Item(id: 'mi428', skillId: 'ms38', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '10 - 4 = ?'),
      answer: ['6'], distractors: ['5', '7', '8']),
  Item(id: 'mi429', skillId: 'ms38', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '8 - 3 = ?'),
      answer: ['5'], distractors: ['4', '6', '7']),
  Item(id: 'mi430', skillId: 'ms39', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '12 - 5 = ?'),
      answer: ['7'], distractors: ['6', '8', '5']),
  Item(id: 'mi431', skillId: 'ms39', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '15 - 8 = ?'),
      answer: ['7'], distractors: ['6', '8', '5']),
  Item(id: 'mi432', skillId: 'ms39', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '18 - 9 = ?'),
      answer: ['9'], distractors: ['8', '10', '7']),
  Item(id: 'mi433', skillId: 'ms39', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '14 - 6 = ?'),
      answer: ['8'], distractors: ['7', '9', '6']),
  Item(id: 'mi434', skillId: 'ms39', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '17 - 8 = ?'),
      answer: ['9'], distractors: ['8', '10', '7']),
  Item(id: 'mi435', skillId: 'ms39', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '20 - 10 = ?'),
      answer: ['10'], distractors: ['9', '11', '8']),
  Item(id: 'mi436', skillId: 'ms39', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '13 - 7 = ?'),
      answer: ['6'], distractors: ['5', '7', '4']),
  Item(id: 'mi437', skillId: 'ms39', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '16 - 9 = ?'),
      answer: ['7'], distractors: ['6', '8', '5']),
  Item(id: 'mi438', skillId: 'ms39', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '19 - 8 = ?'),
      answer: ['11'], distractors: ['10', '12', '9']),
  Item(id: 'mi439', skillId: 'ms39', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '11 - 4 = ?'),
      answer: ['7'], distractors: ['6', '8', '5']),
  Item(id: 'mi440', skillId: 'ms39', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '20 - 7 = ?'),
      answer: ['13'], distractors: ['12', '14', '11']),
  Item(id: 'mi441', skillId: 'ms39', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '15 - 6 = ?'),
      answer: ['9'], distractors: ['8', '10', '7']),
  Item(id: 'mi442', skillId: 'ms40', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '3 + 5 = ?'),
      answer: ['8'], distractors: ['7', '9', '6']),
  Item(id: 'mi443', skillId: 'ms40', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '12 - 7 = ?'),
      answer: ['5'], distractors: ['4', '6', '3']),
  Item(id: 'mi444', skillId: 'ms40', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '9 + 8 = ?'),
      answer: ['17'], distractors: ['16', '18', '15']),
  Item(id: 'mi445', skillId: 'ms40', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '15 - 6 = ?'),
      answer: ['9'], distractors: ['8', '10', '7']),
  Item(id: 'mi446', skillId: 'ms40', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '6 + 7 = ?'),
      answer: ['13'], distractors: ['12', '14', '11']),
  Item(id: 'mi447', skillId: 'ms40', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '18 - 9 = ?'),
      answer: ['9'], distractors: ['8', '10', '7']),
  Item(id: 'mi448', skillId: 'ms40', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '4 + 9 = ?'),
      answer: ['13'], distractors: ['12', '14', '11']),
  Item(id: 'mi449', skillId: 'ms40', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '20 - 11 = ?'),
      answer: ['9'], distractors: ['8', '10', '11']),
  Item(id: 'mi450', skillId: 'ms40', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '7 + 6 = ?'),
      answer: ['13'], distractors: ['12', '14', '15']),
  Item(id: 'mi451', skillId: 'ms40', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '16 - 8 = ?'),
      answer: ['8'], distractors: ['7', '9', '6']),
  Item(id: 'mi452', skillId: 'ms40', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is TRUE?'),
      answer: ['8 + 5 = 13'], distractors: ['8 + 5 = 12', '8 + 5 = 14', '8 + 5 = 15']),
  Item(id: 'mi453', skillId: 'ms40', exerciseType: ExerciseType.pick_text,
      prompt: ItemPrompt(text: 'Which is TRUE?'),
      answer: ['15 - 7 = 8'], distractors: ['15 - 7 = 7', '15 - 7 = 9', '15 - 7 = 6']),

  // ═══════════════════════════════════════════════════════════════════════════
  // M11 – Counting & Number Bonds (ms41-ms43)
  // ═══════════════════════════════════════════════════════════════════════════
  Item(id: 'mi454', skillId: 'ms41', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes after 45?'),
      answer: ['46'], distractors: ['44', '47', '55']),
  Item(id: 'mi455', skillId: 'ms41', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes after 79?'),
      answer: ['80'], distractors: ['78', '81', '70']),
  Item(id: 'mi456', skillId: 'ms41', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes after 99?'),
      answer: ['100'], distractors: ['98', '101', '90']),
  Item(id: 'mi457', skillId: 'ms41', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What number is between 56 and 58?'),
      answer: ['57'], distractors: ['55', '59', '56']),
  Item(id: 'mi458', skillId: 'ms41', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What number is between 89 and 91?'),
      answer: ['90'], distractors: ['88', '92', '80']),
  Item(id: 'mi459', skillId: 'ms41', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Count by 10s: 10, 20, 30, ___'),
      answer: ['40'], distractors: ['35', '50', '41']),
  Item(id: 'mi460', skillId: 'ms41', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Count by 10s: 40, 50, 60, ___'),
      answer: ['70'], distractors: ['65', '80', '71']),
  Item(id: 'mi461', skillId: 'ms41', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Count by 5s: 5, 10, 15, ___'),
      answer: ['20'], distractors: ['18', '25', '21']),
  Item(id: 'mi462', skillId: 'ms41', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Count by 5s: 45, 50, 55, ___'),
      answer: ['60'], distractors: ['58', '65', '61']),
  Item(id: 'mi463', skillId: 'ms41', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes before 63?'),
      answer: ['62'], distractors: ['64', '61', '52']),
  Item(id: 'mi464', skillId: 'ms41', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes before 100?'),
      answer: ['99'], distractors: ['98', '101', '90']),
  Item(id: 'mi465', skillId: 'ms41', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Count on: 87, 88, 89, ___'),
      answer: ['90'], distractors: ['86', '91', '80']),
  Item(id: 'mi466', skillId: 'ms42', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '1 + ___ = 4'),
      answer: ['3'], distractors: ['2', '4', '5']),
  Item(id: 'mi467', skillId: 'ms42', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '2 + ___ = 4'),
      answer: ['2'], distractors: ['1', '3', '4']),
  Item(id: 'mi468', skillId: 'ms42', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '___ + 1 = 4'),
      answer: ['3'], distractors: ['2', '4', '5']),
  Item(id: 'mi469', skillId: 'ms42', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '2 + ___ = 5'),
      answer: ['3'], distractors: ['2', '4', '5']),
  Item(id: 'mi470', skillId: 'ms42', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '___ + 4 = 5'),
      answer: ['1'], distractors: ['2', '3', '4']),
  Item(id: 'mi471', skillId: 'ms42', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '3 + ___ = 5'),
      answer: ['2'], distractors: ['1', '3', '4']),
  Item(id: 'mi472', skillId: 'ms42', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '___ + 4 = 6'),
      answer: ['2'], distractors: ['1', '3', '4']),
  Item(id: 'mi473', skillId: 'ms42', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '3 + ___ = 6'),
      answer: ['3'], distractors: ['2', '4', '5']),
  Item(id: 'mi474', skillId: 'ms42', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '1 + ___ = 6'),
      answer: ['5'], distractors: ['4', '6', '7']),
  Item(id: 'mi475', skillId: 'ms42', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '___ + 5 = 7'),
      answer: ['2'], distractors: ['1', '3', '4']),
  Item(id: 'mi476', skillId: 'ms42', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '4 + ___ = 7'),
      answer: ['3'], distractors: ['2', '4', '5']),
  Item(id: 'mi477', skillId: 'ms42', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: '___ + 6 = 7'),
      answer: ['1'], distractors: ['2', '3', '4']),
  Item(id: 'mi478', skillId: 'ms43', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes after 15 when counting down?'),
      answer: ['14'], distractors: ['16', '13', '15']),
  Item(id: 'mi479', skillId: 'ms43', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes after 8 when counting down?'),
      answer: ['7'], distractors: ['9', '6', '8']),
  Item(id: 'mi480', skillId: 'ms43', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Count down: 20, 19, 18, ___'),
      answer: ['17'], distractors: ['16', '19', '15']),
  Item(id: 'mi481', skillId: 'ms43', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Count down: 12, 11, 10, ___'),
      answer: ['9'], distractors: ['8', '11', '13']),
  Item(id: 'mi482', skillId: 'ms43', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Count down: 7, 6, 5, ___'),
      answer: ['4'], distractors: ['3', '6', '8']),
  Item(id: 'mi483', skillId: 'ms43', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What comes before 10 when counting down from 20?'),
      answer: ['11'], distractors: ['9', '12', '10']),
  Item(id: 'mi484', skillId: 'ms43', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Count down: 15, 14, 13, ___'),
      answer: ['12'], distractors: ['11', '14', '16']),
  Item(id: 'mi485', skillId: 'ms43', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'What number is between 6 and 4 when counting down?'),
      answer: ['5'], distractors: ['7', '3', '6']),
  Item(id: 'mi486', skillId: 'ms43', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Count down: 5, 4, 3, ___'),
      answer: ['2'], distractors: ['1', '4', '6']),
  Item(id: 'mi487', skillId: 'ms43', exerciseType: ExerciseType.pick_number,
      prompt: ItemPrompt(text: 'Count down: 3, 2, 1, ___'),
      answer: ['0'], distractors: ['1', '-1', '4']),
];
